### ISSUE TITLE
el callback deberia contener importe y los fees

### ISSUE THREAD

**Issue by altomarketing** [TodoPago/SDK-PHP#1]
Cuando el sdk vuelve con operacion exitosa, deberia informarme cuando son las tarifas descontadas y cobradas por todopago para poder ponerlo como fees en nuestro sistema.

Ahora solo me dice si esta paga o no.

**Comment by damianwajser** [comment]
Tomo la recomendación y lo hablo con el equipo. Muchas Gracias!

**Comment by altomarketing** [comment]
Paso 10 meses, alguna novedad ?

**Comment by monpac** [comment]
Esto serviría mucho si. No se puede saber al menos que se mire el dashboard o hacer un cálculo estimado previamente.

**Comment by altomarketing** [comment]
Pasó mas de unaño y no pueden agregar una linea de codigo para informar el importe pagado ?

**Comment by monpac** [comment]
Tampoco es "una linea de código" pero creo que es de suma importancia saber el retorno final del comerciante, ya que las comisiones que se aplican a veces son distintas para distintos lugares (ej: Córdoba, donde el costo termina siendo mayor).

Por favor @damianwajser sería muy útil para los desarrolladores y el ecosistema en general.

**Comment by damianwajser** [comment]
Deberías comunicarte con todo pago y solicitar la funcionalidad.
Desde la pagina de todo pago tenes un contacto.
saludos.

**Comment by altomarketing** [comment]
> Deberías comunicarte con todo pago y solicitar la funcionalidad.

En serio @damianwajser ? desde el  ** Oct-2015 al Abril-2017**  ¿ mas de 2 años para esa respuesta ?

No existe el soporte en todopago, las pasarelas que realizamos a veces dan error y la respuesta de soporte es , _no se porque falla tu pago_, no puedo darte información de callback. Fijate vos..
¿Y pretendes que pida nuevas funcionalidades ?

Fijate en https://github.com/TodoPago/SDK-PHP/issues/7 , desde octubre del año pasado preguntando por un error y la respuesta es ... ah, no hay respuesta.

**Comment by fcaivano** [comment]
#7 yo soy el del issue.. Realmente el problema eran cientos de errores no documentados con lo cual era difícil desifrar cual era el problema.

Pedir de poder ver las comisiones/promociones/cft/etc via SDK sería mucho pedir?

**Comment by altomarketing** [comment]
Podrías contarnos que fue lo que pasó y como lo arreglaste.

**Comment by drarko** [comment]
Estimados,
Recientemente se agrego la informacion de los impuestos y comisiones cobradas por TodoPago, las mismas se puede obtener del servicio getStatus luego de un maximo de 3 minutos de realizado el pago.
