### ISSUE TITLE
502 error. Formulario hibrido. Sandbox mode.

### ISSUE THREAD

**Issue by rethPach** [TodoPago/SDK-PHP#10]
Muy buenas.

Al seleccionar el tipo de tarjeta y banco, cuando intento seleccionar el numero de cuotas
arroja el error arriba mencionado.

**Comment by drarko** [comment]
Estimado,

El equipo de TodoPago se encuentra trabajando para solucionar este
inconveniente.

Saludos

**Comment by rethPach** [comment]
Ok, Muchas Gracias.

**Comment by drarko** [comment]
Hola TodoPago/SDK-PHP,
Tienes un mensaje de mauricioghiorzi91 en IQ Elite para ti. 
Haz click aqui a.iqelite.com/j/0NJf2L/nxj/?hg=X69lDQsugm para leer el mensaje 


El equipo de IQ Elite



---------------------------------------------------------------------------
Este mensaje estaba destinado a reply@reply.github.com. Si no deseas seguir recibiendo mensajes de IQ Elite, haz click en este enlace: a.iqelite.com/common/unsubscribe/?code=40df16aa&email=reply@reply.github.com.&hg=X69lDQsugm IQ Elite es un servicio con oficina principal en: C/ Gran de Gràcia 15, 2º 1ª, 08012 Barcelona, España.
---------------------------------------------------------------------------

**Comment by drarko** [comment]
Hola TodoPago/SDK-PHP,


Tienes un mensaje de mauricioghiorzi91 en IQ Elite para ti. 


Haz click aqui a.iqelite.com/j/0NJf2L/nxj/?hg=pkFmiWowxQ para leer el mensaje 


El equipo de IQ Elite



---------------------------------------------------------------------------
Este mensaje estaba destinado a reply@reply.github.com. Si no deseas seguir recibiendo mensajes de IQ Elite, haz click en este enlace: a.iqelite.com/common/unsubscribe/?code=40df16aa&email=reply@reply.github.com.&hg=pkFmiWowxQ IQ Elite es un servicio con oficina principal en: C/ Gran de Gràcia 15, 2º 1ª, 08012 Barcelona, España.
---------------------------------------------------------------------------
