### ISSUE TITLE
Fecha de pago incorrecta

### ISSUE THREAD

**Issue by nicoreg** [TodoPago/SDK-PHP#11]
Al generar una solicitud de pago utilizando sendAuthorizeRequest() en una fecha, cuando se recibe ese pago se recibe con la fecha de creación de la solicitud y no con la fecha real de pago.
Por ejemplo: un pago se genera el 1ro de diciembre usando sendAuthorizeRequest() luego el pago se hace efectivo el día 12 de diciembre. Cuando se lo ve desde la web de todopago.com.ar o bien se lo recibe usando getByRangeDateTime() el pago figura en el JSON como del 1ro de diciembre cuando la operación se realizó el 12 de diciembre.
La plata se libera como si fuera del 12 de diciembre, por ende no se si es un problema del SDK o del sistema interno de todopago.
Saludos,

Nicolás

**Comment by drarko** [comment]
Estimado,
Actualmente los pagos deben realizarse dentro de 6hs como maximo de la llamada al SAR
Tomamos igualmente el error y lo elevamos al equipo correspondiente.

Se cierra ya que no es error de la SDK.
