### ISSUE TITLE
Error "98203" ?

### ISSUE THREAD

**Issue by fcaivano** [TodoPago/SDK-PHP#15]
Hola,

Podrían documentar el error 98203, que razón tiene.

Y de ser posible actualizar la lista de errores con cualquier otro que pudiera faltar.

Gracias!

**Comment by unrblt** [comment]
Hola. A mi me reportaron este [error](https://www.drupal.org/node/2893354) en el módulo que integra todopago con drupal commerce. Según las pruebas que hicimos el error se da porque en el campo `CSITPRODUCTNAME` hay menos elementos que la cantidad de productos del carrito. Osea, al concatenar todos los nombres de producto separados por `#` y recortar el campo a 255 caracteres se pierden los nombres de algunos productos. Pasa lo mismo con `CSITPRODUCTDESCRIPTION` (error `98202`). Lo que hicimos fue recortar cada nombre o descripción antes de concatenarlos para asegurar que no pase de 255 caracteres pero que tampoco falten nombres de productos.

**Comment by drarko** [comment]
Tabla de errores:
https://github.com/TodoPago/SDK-PHP#interrores
