### ISSUE TITLE
Esta operación no admite medios de pago en efectivo.

### ISSUE THREAD

**Issue by guidogonz23** [TodoPago/SDK-PHP#18]
Quisiera habilitar el pago en efectivo. Hice la integracion con PHP pero me sale esto: 

Esta operación no admite medios de pago en efectivo.

Hay que incluir algun codigo?

**Comment by alejandro021987** [comment]
Que tal @guidogonz23, por el momento TodoPago no ofrece medios de pago en efectivo para hacer pagos offline como por ejemplo RapiPago o PagoFacil  pero si ahora se cuenta con PEI que es para hacer pagos con tarjeta de debito. Saludos
