### ISSUE TITLE
Redeclare getEndpointForm()

### ISSUE THREAD

**Issue by kimonoapps** [TodoPago/SDK-PHP#19]
Hola, por algun motivo (Error Humano) en el SDK 1.8.2 quedo redeclarado el metodo getEndpointForm()

Copio el error:
Fatal error:  Cannot redeclare TodoPago\Sdk::getEndpointForm() 

Basicamente el problema es que quedo 2 veces copiado el metodo "public function getEndpointForm($mode = null)" en la linea 45 y 60

Atte.
Rolando

**Comment by drarko** [comment]
Buenas tardes estimado,
Ya esta solucionado, muchas gracias por el reporte.

Saludos
