### ISSUE TITLE
Feature: En sdk no puedo poner mi logo, ni mis datos

### ISSUE THREAD

**Issue by altomarketing** [TodoPago/SDK-PHP#2]
Deberian permitir poner mi logo, imagen remota o algun dato que le permita a la persona que esta abonando, que vea a quien le esta pagando, tal como generando un boton a mano, puedo poner imagenes, etc.

**Comment by damianwajser** [comment]
Estamos analizando la personalización del checkout para los proximos releases.
Gracias por el comentario.
Slds!

**Comment by altomarketing** [comment]
Esto fue en 16 Oct 2015 , alguna novedad ?
