### ISSUE TITLE
Ejemplo solo para generar botones 

### ISSUE THREAD

**Issue by EOM** [TodoPago/SDK-PHP#20]
Hola una pregunta no tiene un ejemplo que permita crear el link para poner en un sector del sitio por medio del SDK..?
Como lo tiene MercadoPago. Donde si permite crear un botón con el link el cual permite ademas sin ningún dato pasado por el usuario generar ese link.

La idea es generar un link, con el total de nuestro carrito de compra según el cliente en el momento de pagar y que lo mande a su pagina para pagar al darle click en el botón "Pagar por Todo Pago" y ustedes se encargan del resto, nosotros no le pedimos ningún dato previo al cliente.
Esto el SDK de MercadoPago lo permite hacer muy simple.

Gracias y espero su respuesta si hay forma de hacerlo con el SDK de TodoPago

**Comment by damianwajser** [comment]
Por el momento la api generadora de botones no es pública.

**Comment by EOM** [comment]
Yo vi que lo pude generar el link que busco para poner en un botón.

Pero no puedo cree que tenga que tener toda esta información antes de poder generar el link ademas con el link que genera el cliente tiene que volver a cargar el formulario dentro de TodoPago, solo tiene dos o tres datos.

Pregunta que pasa si yo implemento la opción para generar el link siempre con los mismos datos de esta manera tengo la opción de generar un link sin pedir todo esa información a los clientes, porque no queremos guarda ningún dato de los clientes en los servers, queremos que se comporte como los hace MercadoPago que si lo permite y el tema de los datos queda para ustedes desde su servidores.

Por ejemplo los datos que podria utilizar siempre para generar el link como hice, podria ser lo de cada comercio que utilizar el plugin que estoy desarrollando para CakePHP

Si se puede de esta manera lo tendría solucionado al problema y puedo generar los links para el <a href="xxxx" como busco. 

$optionsSAR_operacion = array(      
    ...........................................................................     
    'CSBTCITY'=>'Villa General Belgrano', //Ciudad de facturación, MANDATORIO.     
    'CSBTCOUNTRY'=>'AR', //País de facturación. MANDATORIO. Código ISO. (http://apps.cybersource.com/library/documentation/sbc/quickref/countries_alpha_list.pdf)        
    'CSBTCUSTOMERID'=>'453458', //Identificador del usuario al que se le emite la factura. MANDATORIO. No puede contener un correo electrónico.        
    'CSBTIPADDRESS'=>'192.0.0.4', //IP de la PC del comprador. MANDATORIO.      
    'CSBTEMAIL'=>'midirecciondemail@hotmail.com', //Mail del usuario al que se le emite la factura. MANDATORIO.     
    'CSBTFIRSTNAME'=>'Juan' ,//Nombre del usuario al que se le emite la factura. MANDATORIO.        
    'CSBTLASTNAME'=>'Perez', //Apellido del usuario al que se le emite la factura. MANDATORIO.      
    'CSBTPHONENUMBER'=>'541160913988', //Teléfono del usuario al que se le emite la factura. No utilizar guiones, puntos o espacios. Incluir código de país. MANDATORIO.     
    'CSBTPOSTALCODE'=>' C1010AAP', //Código Postal de la dirección de facturación. MANDATORIO.       
    'CSBTSTATE'=>'B', //Provincia de la dirección de facturación. MANDATORIO. Ver tabla anexa de provincias.      
    'CSBTSTREET1'=>'Cerrito 740', //Domicilio de facturación (calle y nro). MANDATORIO.        
    'CSBTSTREET2'=>'Piso 8', //Complemento del domicilio. (piso, departamento). NO MANDATORIO.      
    'CSPTCURRENCY'=>'ARS', //Moneda. MANDATORIO.        
    'CSPTGRANDTOTALAMOUNT'=>'125.38', //Con decimales opcional usando el punto como separador de decimales. No se permiten comas, ni como separador de miles ni como separador de decimales. MANDATORIO. (Ejemplos:$125,38-> 125.38 $12-> 12 o 12.00)               
    'CSMDD7'=>'', // Fecha registro comprador(num Dias). NO MANDATORIO.     
    'CSMDD8'=>'Y', //Usuario Guest? (Y/N). En caso de ser Y, el campo CSMDD9 no deberá enviarse. NO MANDATORIO.        
    'CSMDD9'=>'', //Customer password Hash: criptograma asociado al password del comprador final. NO MANDATORIO.        
    'CSMDD10'=>'', //Histórica de compras del comprador (Num transacciones). NO MANDATORIO.        
    'CSMDD11'=>'', //Customer Cell Phone. NO MANDATORIO.        
    'CSSTCITY'=>'rosario', //Ciudad de enví­o de la orden. MANDATORIO.        
    'CSSTCOUNTRY'=>'', //País de envío de la orden. MANDATORIO.       
    'CSSTEMAIL'=>'jose@gmail.com', //Mail del destinatario, MANDATORIO.     
    'CSSTFIRSTNAME'=>'Jose', //Nombre del destinatario. MANDATORIO.     
    'CSSTLASTNAME'=>'Perez', //Apellido del destinatario. MANDATORIO.       
    'CSSTPHONENUMBER'=>'541155893737', //Número de teléfono del destinatario. MANDATORIO.
    'CSSTPOSTALCODE'=>'1414', //Código postal del domicilio de envío. MANDATORIO.     
    'CSSTSTATE'=>'D', //Provincia de envío. MANDATORIO. Son de 1 caracter      
    'CSSTSTREET1'=>'San Martín 123', //Domicilio de envío. MANDATORIO.        
    'CSMDD12'=>'',//Shipping DeadLine (Num Dias). NO MADATORIO.     
    'CSMDD13'=>'',//Método de Despacho. NO MANDATORIO.     
    'CSMDD14'=>'',//Customer requires Tax Bill ? (Y/N). NO MANDATORIO.      
    'CSMDD15'=>'',//Customer Loyality Number. NO MANDATORIO.        
    'CSMDD16'=>'',//Promotional / Coupon Code. NO MANDATORIO.       
    //Retail: datos a enviar por cada producto, los valores deben estar separados con #:        
    'CSITPRODUCTCODE'=>'electronic_good', //Código de producto. MANDATORIO. Valores posibles(adult_content;coupon;default;electronic_good;electronic_software;gift_certificate;handling_only;service;shipping_and_handling;shipping_only;subscription)     
    'CSITPRODUCTDESCRIPTION'=>'NOTEBOOK L845 SP4304LA DF TOSHIBA', //Descripción del producto. MANDATORIO.     
    'CSITPRODUCTNAME'=>'NOTEBOOK L845 SP4304LA DF TOSHIBA', //Nombre del producto. MANDATORIO.      
    'CSITPRODUCTSKU'=>'LEVJNSL36GN', //Código identificador del producto. MANDATORIO.      
    'CSITTOTALAMOUNT'=>'1254.40', //CSITTOTALAMOUNT=CSITUNITPRICE*CSITQUANTITY "999999[.CC]" Con decimales opcional usando el punto como separador de decimales. No se permiten comas, ni como separador de miles ni como separador de decimales. MANDATORIO.       
    'CSITQUANTITY'=>'1', //Cantidad del producto. MANDATORIO.       
    'CSITUNITPRICE'=>'1254.40', //Formato Idem CSITTOTALAMOUNT. MANDATORIO.

**Comment by damianwajser** [comment]
Las herramientas de riesgo te van a empezar a rechazar los datos.
Por favor comunícate con soporte técnico comercial de todo pago. El
contacto esta en la pagina.. capaz te pueden guiar mejor.

Gracias.
Slds.

**Comment by EOM** [comment]
Ok gracias por tu pronta respuesta, espero que en el futuro cercano tengan esta opción como otro de la competencia tienen desde hace años.
Saludos
