### ISSUE TITLE
A Reflected XSS vulnerability in this sdk

### ISSUE THREAD

**Issue by jgj212** [TodoPago/SDK-PHP#21]
Hello:
I found a Reflected XSS vulnerability in this sdk.

The vulnerability exists due to insufficient filtration of user-supplied data in 'operationid' HTTP _GET parameter that will be passed to “SDK-PHP-master\resources\ejemplo_1\exito.php”. The infected source code is line 30,  there is no protection on $_GET['operationid']; If $_GET['operationid'] contains evil js code, line 30 will trigger untrusted code to be excuted on the browser side
>
![code1](https://cloud.githubusercontent.com/assets/1484292/23251884/c129aeea-f9e9-11e6-9b77-e2a015be5d0a.png)

So if a attacker construct a special url as follow and send it to a victim, when the victim click the url, the code which is contained in the url will be executed on the victim's browser side to do some evil.
http://your-web-root/SDK-PHP-master/resources/ejemplo_1/exito.php?operationid="><script>alert(1);</script><"

The follow screenshot is the result to click the upper url ( win7 sp1 x64 + firefox 51.0.1 32bit ):
>
![sc](https://cloud.githubusercontent.com/assets/1484292/23251960/0f40bf88-f9ea-11e6-9a40-c9bb6111b138.png)

Discoverer: Haojun Hou, DongWang in ADLab of Venustech
Email: jgj212@gmail.com

**Comment by EOM** [comment]
Huu si mal.. es verdad.. igual yo lo tome como que era una ejemplo base eso de "exito.php" no que va a producción como esta..
Solución rápida http://php.net/manual/es/function.strip-tags.php sobre los paramtros GET o alguna exprecion regular que solo deja numero y letra, sin espacios.

Pero la mejor técnica de respuesta es JWT https://jwt.io/ y por post al server no por get

Saludos y de nada ;-)

**Comment by damianwajser** [comment]
Es un ejemplo solamente para que se entienda el flujo de información....
luego la implementacion  depende de los comercios.
Por otro lado el orden id no te sirve de mucho no es un dato crítico... y
todas las interacciones con todopago son server side.

**Comment by jgj212** [comment]
Does it mean that  "SDK-PHP-master\resources\ejemplo_1\exito.php" is invisible to the browser side?

**Comment by EOM** [comment]
@damianwajser 
Por mas que sea un ejemplo muchos PHP novatos implementan como están los ejemplos por eso esta bueno hacerlo bien en el ejemplo también.
Y el problema no es el numero de orden, si no que es la inyección de código, por ejemplo que se puede hacer un XSS, insertar un iframe, y volver a pedir datos como que fallo algo y roban los datos. Hacer un sitio clon de TodoPago para robar datos, etc..  Atacar por medio del sitio a otros sitio que no tiene nada que ver con span, etc... eso son algunas de las cosas que se puede hacer con eso.
Saludos

**Comment by EOM** [comment]
@jgj212
[ES]: Claro que no, exito.php y error.php son publicos.

[EN]: Of course not, exito.php and error.php are public

**Comment by EOM** [comment]
If Google Translator is bad.
My english is but bad ;-(
I confirm @jgj212 that what you wrote in the previous message is what to comment on @damianwajser. That is the danger.
Regards

**Comment by jgj212** [comment]
@EOM  thank you

**Comment by drarko** [comment]
Fixed. Thanks
