### ISSUE TITLE
SQL de las tablas Provincia y COUNTRY ..?

### ISSUE THREAD

**Issue by EOM** [TodoPago/SDK-PHP#22]
Hola porque no agregar en el SDK los SQL para las Provincias.sql y Country.sql Si no hay que salir a buscarlo por internet o crear lo a mano ;-(

**Comment by drarko** [comment]
Estimado,
Se incluye en la documentacion la tabla de Provincias y sus resectivos codigo asi como tambien se indica que para el pais debe enviarse el codigo ISO.

No podemos agregar un script sql ya que depende de la implementación realizada y excede al SDK. Se analizara la inclusion en algun ejemplo futuro.

Gracias
