### ISSUE TITLE
Error en DOC SDK-PHP/README.md que es "Conditional"..?

### ISSUE THREAD

**Issue by EOM** [TodoPago/SDK-PHP#23]
En los parámetro no es claro que es "Conditional"..?
Ya que los campo tiene que ser "Requerido" o "Opcional" y muchos de los "Conditional" por mis test veo que son "Requerido". 
Puede detallar mejor eso.?

- AMOUNT No Existe en el detalle de parametros, ni tipo de dato, minimo, ni que es requerido, etc..
- CSSTSTREET2 Porque ponen en el doc que es "Barro" y en el ejemplo ponen el "Departamento" cuando tendría que ser otra calle.
- CSITTOTALAMOUNT Falta el tipo de dato que es, me imagino que es Decimal(15,2)
- CSITUNITPRICE Ponen que es String(15) pero me imagino que es Decimal(15,2)
- CSPTCURRENCY En el ejemplo del código ponen 'ARS' y el la descripción ponen que es '032'

> Eso por nombrar algunos error de consistencias en la documentación y el código, yo no puedo crear que están saliendo con un producto tan verde al mercado. Sobretodo teniendo a VISA por detrás que tiene para invertir. Disculpen por la catarsis ;)

**Comment by EOM** [comment]
Ahh mi recomendación es que creen un SQL con todos los parámetros que piden en una tabla SQL para que  lo tengan desarrollos que crean proyecto a medida, como es mi caso ;-)

**Comment by drarko** [comment]
Estimado,
Se ha mejorado el formato de la documentacion. 
Saludos
