### ISSUE TITLE
Botón de pago, SDK-PHP

### ISSUE THREAD

**Issue by AgustinQuetto** [TodoPago/SDK-PHP#25]
Hola, buenas tardes.

Poseo la siguiente duda...

Comprendo que mediante la API, mi web procesa el array recibido para saber la información de respuesta y elegir que hacer con aquellos datos (los del cliente y tipo success).

Los botones de pago de TodoPago que se crean en el panel, ¿envían algún tipo de información tipo GET al finalizar la compra?

Mediante el SDK, ¿puedo utilizar esta interfaz obteniendo información posteriormente desde la API? 
https://forms.todopago.com.ar/formulario/commands?command=formulario&m=5f800ea393ad9238f0c77d93a509858c#utm_source=357382&utm_medium=boton_de_pago&utm_campaign=web

Si alguno tiene otro ejemplo funcional, aparte de los brindados para darme, se lo agradecería.
Gracias.

**Comment by AgustinQuetto** [comment]
¿Saben si luego de la transacción por el botón generado se envían POST a exito/error?

**Comment by drarko** [comment]
@AgustinQuetto los botones creados desde el portal no poseen esta funcionalidad.
La SDK no opera con botones de pago.
Saludos

**Comment by AgustinQuetto** [comment]
@drarko ¡Gracias por tu respuesta! Conclusión... la única forma de recibir una respuesta con datos a una página es mediante el SDK. Genial. ¡Saludos!
