### ISSUE TITLE
Error cuando un producto tiene caracteres reservados

### ISSUE THREAD

**Issue by lombo** [TodoPago/SDK-PHP#26]
Versión 1.8.2

Si el producto tiene un & en el nombre, no se puede generar el Authorize Request. No probé para otros campos ni para otros caracteres reservados. Como son implementation details, deberían escaparse en la SDK.

# Pasos para reproducir

Llamar a `sendAuthorizeRequest` con al menos un producto con el caracter `&` en su nombre (campo CSITPRODUCTNAME).

# Esperado

Procesar el Authorize Request correctamente

# Obtenido

javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1195]\nMessage: The entity name must immediately follow the '&' in the entity reference.

**Comment by drarko** [comment]
Solucionado en el ultimo release. Saludos
