### ISSUE TITLE
Identificar cada pago de un boton de pago

### ISSUE THREAD

**Issue by rstaiti** [TodoPago/SDK-PHP#27]
Necesito saber si hay alguna forma de identificar cada pago de un mismo boton de pago. Es decir si yo genero un boton de pago para una empresa. Quiere pasarle parametros al formulario de todo pago para poder identificar la reserva con un numero y el nombre de la persona. O bien si se puede desde la api generar botones identificándolos de alguna manera.

**Comment by drarko** [comment]
Estimado,
Desde la SDK no es posible generar botones ni recibir información de los pagos de los mismos.
Los botones se administran enteramente por el Portal.
