### ISSUE TITLE
Error al querer levantar la pagina de pago desde php

### ISSUE THREAD

**Issue by triabox** [TodoPago/SDK-PHP#28]
Cuando ejecuto en el ambiente de prueba desde php para que me levante la ventana de pago tengo el siguiente error:

Reason: Error reading from remote server

la url ejecutada es: https://developers.todopago.com.ar/formulario/commands?command=formulario&m=t126ad190-efe9-9c21-478e-f3c7a0f24be1

adjunto imagen
![captura](https://cloud.githubusercontent.com/assets/18578909/24057164/2ae326bc-0b25-11e7-8ae7-3f35c59db13e.JPG)

**Comment by triabox** [comment]
ya esta funcionando, parece que estaba caido

**Comment by drarko** [comment]
Estimado
Fue un error temporal 
Saludos
