### ISSUE TITLE
TIMEOUT --> 6 hs maximo ?

### ISSUE THREAD

**Issue by matiazar** [TodoPago/SDK-PHP#30]
No entiendo este parametro.. o sea.. vino un cliente a mi sitio.. genero un carrito, selecciono pagar con TodoPago.
Le mando un mail para que acceda al portal y pague.. pero decide pagarlo en un rato... ese rato se le pasa y lo va a realizar al otro dia !... pero OUCH el pago ya no puede ser realizado.

O sea. tiene que volver a armar el carrito de compra desde cero en mi portal !

**Comment by Thargelion** [comment]
Hoy en día depende de cómo trabaje el plugin. De todos modos, está planeado añadirse la elección de vaciar o no el carrito en caso de fallas como el timeout en próximas versiones de los plugins.
Saludos.

**Comment by fcaivano** [comment]
Más allá de que el issue esta cerrado, por si sirve de tip para @matiazar o cualquier otro que llegue al issue.

Creo que tu planteo parte de un error en el diseño de tu carrito.

El carrito debería de (en caso que requieras de esto) almacenar en algún lugar los productos seleccionados (ya sea eternamente, o que otro proceso los limpie cada X tiempo luego de no ser revisados).

De esta forma solo al momento de pagar inicias la transacción con TodoPago (o el procesador de pagos que sea) y tenes la posibilidad de que tu usuario complete la compra en cualquier momento aún si pasen 100 dias...

Esto es algo por ejemplo muy común en Amazon, que juega con dejarte eternamente tus productos seleccionados además de recomendarte otros similares. Eventualmente un buen % termina cerrando esa compra que inicialmente no hizo.
