### ISSUE TITLE
Operaciones pendientes

### ISSUE THREAD

**Issue by diegomarpla** [TodoPago/SDK-PHP#34]
Buenas tardes.
Estoy realizando las primeras pruebas de integración, por ahora estoy teniendo buenos resultados con operaciones aprobadas y rechazadas, aunque el entorno de pruebas es pésimo ya que ingresar al entorno developer es prácticamente imposible. 
Mi consulta es sobre las operaciones que quedan en estado "Pendiente".
Por ejemplo:
Al ser aprobadas redirige a exito.php
Al ser rechazado redirige a rechazo.php
En ambos casos se realizan las operaciones correspondientes.

Al ser aprobada el StatusCode de sendAuthorizeRequest es = -1
Al ser rechazado es distinto, se captura el codigo y el error correspondiente.

Hasta ahí todo tranquilo. Dudas:

No entiendo el estado 99900 "El pago fue realizado exitosamente"...en que situación pasa esto ? y en que difiere con el StatusCode -1 ?

Pero lo que mas me importa es cuando una operación queda pendiente... que estado devuelve ?
Cuando cambia el estado como me llega la notificación ?

Por ejemplo en MercadoPago toda la comunicación se realiza mediante una URL de notificaciones, y existen tres estados iniciales de la operacion, aprobado, rechazado y pendiente, entonces yo sé de entrada que le informo a mi cliente segun ese resultado. Posteriormente si cambia el estado por haber quedado en pendiente me lo comunica mediante la url de notificaciones y yo puedo tomar las medidas correspondientes.
Pero acá no tengo, aparentemente el estado pendiente por lo tanto no sé de que manera reacciona el sistema cuando se encuentra con una operación pendiente de aprobación.

Cualquier comentario se los voy a agradecer.

Saludos

**Comment by drarko** [comment]
Estimado, 
El resultado de las operaciones es online, en caso de que no se pueda procesar la transacción, la misma genera un codigo de rechazo. No existe el estado Pendiente para una transacción.

Saludos

**Comment by azche** [comment]
Hola buen día! 'No existe el estado Pendiente para una transacción' sigue siendo válido? o ya ha cambiado? Gracias!

**Comment by curcio79** [comment]
@ngrunfeld  el estado pendiente solo sigue para los pagos offline, o para aquellos pagos que tengan algun problema en el proceso hasta su verificacion
