### ISSUE TITLE
Problemas con sendAuthorizeRequest

### ISSUE THREAD

**Issue by xeduardomx** [TodoPago/SDK-PHP#36]
Al ejecutar esta línea: 
$rta = $connector->sendAuthorizeRequest($optionsSAR_comercio, $optionsSAR_operacion);
el proceso se pone lento, algunas veces me devuelve la ruta para ir al formulario otras no.

-No entiendo por que a veces esta rapido y responde bien pero ultimamente se cae, no abre, da error, se pone lento, eso logicamente afecta el dedarrollo que estoy llevando a cabo ya que no puedo hacer pruebas ni implementar bien el procesador de pago.

-Cabe destacar que estoy ejecutando el ejemplo simple descargado aquí (resources del SDK, ejemplo) y es demasiado lento y no abre.

En esta ruta tengo el ejemplo en funcionamiento, deberia servir pero nada.
lo mismo pasa cuando intento consultar el estado de un pago, se queda esperando la respuesta.

¿A alguien mas le sucede?

http://igluehost.com/todo/resources/ejemplo_1/checkout.php

Les agradezco cualquier ayuda ya que no logro entregar el trabajo por las fallas en este procesador de pagos, no logro terminar cosas sencillas por que no termina de responder la plataforma.

Ojo tengo una implementación en una WEB y falla y al ejecutar el ejemplo simple descargado da exactamente el mismo problema así que no es mi codigo, ya que lo que hice fue poner datos de prueba en el SAR en cuanto a costos, etc, logicamente usando mi id de comercio y llaves especificas.

Cabe destacar que el ejemplo del enlace hay dias que funciona sin problemas y otros no, eso me hace pensar que no tengo nada mal y el problema viene de la API.

Si alguien sabe le agradezco. 
Saludos

**Comment by xeduardomx** [comment]
¿Nadie da soporte en este foro?

**Comment by alejandro021987** [comment]
Que tal @xeduardomx , esto que comentas que te sucedió fué por que hubo un problema en ese momento que fue solucionado, no era algo propio del sdk. Gracias por notificar este incidente de todas formas. 
Saludos

**Comment by LaureanoR** [comment]
hola @alejandro021987 , tengo el mismo problema que @xeduardomx. Puede ser que sigan habiendo problemas? publiqué mi issue para que me puedan orientar.
Gracias

**Comment by gabrielcinalli** [comment]
Hola me pasa lo mismo....

$rta = $connector->sendAuthorizeRequest($optionsSAR_comercio, $optionsSAR_operacion);
var_dump($rta);

No devuelve ningún valor. Que puede ser?

Mi código:

<?php

use TodoPago\Sdk;
	
//importo archivo con SDK
include_once '../../vendor/autoload.php';

//común a todas los métodos
$http_header = array('Authorization'=>'TODOPAGO b4b3d845dc4e436e9c5dc0636xxxxxxx',
 'user_agent' => 'PHPSoapClient');

$operationid = rand(1,100000000);

//opciones para el método sendAuthorizeRequest

$optionsSAR_comercio = array (
	'Security'=>'b4b3d845dc4e436e9c5dc0636xxxxxxx',
	'EncodingMethod'=>'XML',
	'Merchant'=>833789,
	'URL_OK'=>"http://".$_SERVER['SERVER_NAME'].":".$_SERVER['SERVER_PORT'].str_replace ($_SERVER['DOCUMENT_ROOT'], '', dirname($_SERVER['SCRIPT_FILENAME']))."/exito.php?operationid=$operationid",
	'URL_ERROR'=>"http://".$_SERVER['SERVER_NAME'].":".$_SERVER['SERVER_PORT'].str_replace ($_SERVER['DOCUMENT_ROOT'], '', dirname($_SERVER['SCRIPT_FILENAME']))."/error.php?operationid=$operationid"
);


$optionsSAR_operacion = array (
	'MERCHANT'=> '833789',
	'OPERATIONID'=>"01",
	'CURRENCYCODE'=> 032,
	'AMOUNT'=>"54",
	'EMAILCLIENTE'=>"gab@ssd.com"
	);
	
//opciones para el método getAuthorizeAnswer
$optionsGAA = array(	
	'Security' => 'b4b3d845dc4e436e9c5dc0636xxxxxxx', 
	'Merchant' => '833789',
	'RequestKey' => '8496472a-8c87-e35b-dcf2-94d5e31eb12f',
	'AnswerKey' => '8496472a-8c87-e35b-dcf2-94d5e31eb12f'
	);
	
//opciones para el método getAllPaymentMethods
$optionsGAMP = array("MERCHANT"=>833789);
	
//opciones para el método getStatus 
$optionsGS = array('MERCHANT'=>'833789', 'OPERATIONID'=>'141120084707');
	
//creo instancia de la clase TodoPago
$connector = new Sdk($http_header,"test");

//ejecuto los métodos
$rta = $connector->sendAuthorizeRequest($optionsSAR_comercio, $optionsSAR_operacion);
$rta2 = $connector->getAuthorizeAnswer($optionsGAA);
$rta3 = $connector->getAllPaymentMethods($optionsGAMP);
$rta4 = $connector->getStatus($optionsGS);    
   	 
//imprimo respuestas
echo "<h3>var_dump de la respuesta de Send Authorize Request</h3>";
var_dump($rta);
echo "<h3>var_dump de la respuesta de Get Authorize Answer</h3>";
var_dump($rta2);
echo "<h3>var_dump de la respuesta de Get All Payment Methods</h3>";
var_dump($rta3);
echo "<h3>var_dump de la respuesta de Get Status</h3>";
var_dump($rta4);

**Comment by curcio79** [comment]
@gabrielcinalli buenos dias, fijate que tenes un archivo log dentro de la SDK que te va a dar el motivo del error, lo que si te pido q generes otro issue asi lo podemos seguir especificamente. Espero tu comentario. Saludos
