### ISSUE TITLE
StatusCode: 2013 $resp = $connector->voidRequest($options);

### ISSUE THREAD

**Issue by xeduardomx** [TodoPago/SDK-PHP#38]
Intento hacer una devolución, envio los datos Security, Merchant, RequestKey (que previamente guardo en bd cuando genero) y por ultimo hago prueba enviando AMOUNT y otra sin enviar AMOUNT para que sea total y en ambos casos retorna
StatusCode: 2013 respuesta devol 
StatusMessage: No es posible obtener los importes de las comisiones para realizar la devolucion

**Comment by drarko** [comment]
Estimado, 
Este error se da cuando la transacciòn aun no se encuentra liquidada. 
Por favor, espere unos minutos e intente nuevamente.
Saludos
