### ISSUE TITLE
Error Fetching http headers

### ISSUE THREAD

**Issue by hardkito** [TodoPago/SDK-PHP#39]
# SDK-PHP | Issue Técnico

Hola, a partir de hoy al mediodía comenzamos a recibir el error **Error Fetching http headers** desde el servidor de TP al intentar cargar el formulario de pago personalizado. Solamente pasa en ambiente PROD no asi en TEST que funciona correctamente.

En el servidor del ecommerce no se modificó nada y súbitamente comenzó a producirse este inconveniente con el formulario de pago.

**Comment by oclauz** [comment]
Hola, me sucede los mismo desde las 11 horas de hoy aproximadamente.
El error, si se extiende el timeout, es: **[HTTP] Bad Gateway**
Por lo que deduzco que tienen problemas con el servidor donde se ejecutan las autorizaciones.

**Comment by faculezcano** [comment]
Hola, tengo el mismo problema desde hoy a las 11 horas cuando se pide la autorizacion para ir al formulario de todo pago no hay respuesta.

**Comment by lucasfuentes** [comment]
Lo mismo me pasa a mi....

**Comment by hardkito** [comment]
Respuesta actual:
 **Service Temporarily Unavailable**

Ya van 7 horas y no hay respuesta oficial que informe sobre lo que está pasando en la plataforma. Lo ciero es que no se pueden procesar pagos desde el checkout personalizado en PROD.

**Comment by alejandro021987** [comment]
Hola @hardkito , @oclauz, @faculezcano, @lucasfuentes , esto que notificaron se debio a un problema temporal que ya fue solucionado. Actualmente esta funcionando correctamente tanto para formulario hibrido como para formulario externo. 
saludos!

**Comment by rmnr17** [comment]
pues si fue solucionado a mi me sigue saliendo y ya me tiene podrida todo pago. Error en particular Error al validar datos. Error Fetching http headers
