### ISSUE TITLE
Error Javascript 404

### ISSUE THREAD

**Issue by dsurra** [TodoPago/SDK-PHP#42]
Usando la version 1.10.0 y 1.20.1 da un error con el js https://developers.todopago.com.ar/resources/TPHybridForm-v0.1.js devuelve 404

**Comment by dsurra** [comment]
Agrego un comentario probé con el js que esta en el readme del dev-master https://developers.todopago.com.ar/resources/v2/TPBSAForm.min.js y el form de ejemplo Hibrid Form no funciona por campos inexistentes.
Alguien puede darme una mano?

**Comment by nati08** [comment]
Buuenas, estoy teniendo el mismo problema. Al actualizar el js, me dejó de andar el formulario hibrido. Y ya tenemos un sitio en producción con este plugin.

**Comment by dsurra** [comment]
@nati08  Nosotros tuvimos que hacer ingenieria inversa desde el js v2, y probando lo resolvimos. Tene presente que ahora ha cambiado el formulario, antes elegias los medios de pago y ahora solamente tendrás que poner el número de tarjeta y se rellena el formulario.
Pero es un laburito importante.
Sería muy bueno que se documente mejor el plugin y los ejemplos, al menos que dejen productiva la versión anterior.
Otra cosa no menor en packagist aún no se ha actualizado tampoco el último release (que tiene un error en el js usado)

**Comment by curcio79** [comment]
@dsurra nos disculpamos por la demora en la respuesta y lamentamos mucho que hayas tenido este inconveniente. Me alegra q lo hayas podido resolver, cualquier otro problema contactanos
