### ISSUE TITLE
ResultCode 2053 Tu compra no pudo ser procesada. Comunicate con tu vendedor.

### ISSUE THREAD

**Issue by faculezcano** [TodoPago/SDK-PHP#43]
Hola que tal? tengo la plataforma funcionando hace mucho y recientemente estoy recibiendo muchos codigos de error de este tipo. Es un problema mio o un bug?

**Comment by drarko** [comment]
@faculezcano por favor, comunicate con el 0800 o envia tu consulta a traves del formulario de contacto del Portal.
Muchas gracias
