### ISSUE TITLE
La pasarela de pago falla con Error 99978, 99979 o 2053

### ISSUE THREAD

**Issue by faculezcano** [TodoPago/SDK-PHP#44]
Buenas tardes, con algunos clientes me pasa que la pasarela me devuelve a URL_ERROR con codigo 99979, me comunique por telefono y lo unico que me respondieron fue que era por algo de seguridad que se rebota al cliente. Lo unico que me trae sospechas es que lo rebote el control de fraude?

Les paso el arreglo de operacion y la respuesta a ver si me pueden orientar en donde este el dato dudoso.

# Operation:
{
   "MERCHANT":"XXXXX",
   "OPERATIONID":"1518298555-2927-443-633-1-8",
   "CURRENCYCODE":26,
   "AMOUNT":"47.25",
   "AVAILABLEPAYMENTMETHODSIDS":"1#2#6#13#14#30#42#43#129#900",
   "EMAILCLIENTE":"XXX@hotmail.com",
   "CSBTCITY":"Bahia Blanca",
   "CSSTCITY":"Bahia Blanca",
   "CSBTCOUNTRY":"AR",
   "CSSTCOUNTRY":"AR",
   "CSBTEMAIL":"XXX@hotmail.com",
   "CSSTEMAIL":"XXX@hotmail.com",
   "CSBTFIRSTNAME":"Maximo",
   "CSSTFIRSTNAME":"Maximo",
   "CSBTLASTNAME":"Pirinu",
   "CSSTLASTNAME":"Pirinu",
   "CSBTPHONENUMBER":"542915091865",
   "CSSTPHONENUMBER":"542915091865",
   "CSBTPOSTALCODE":8000,
   "CSSTPOSTALCODE":8000,
   "CSBTSTATE":"B",
   "CSSTSTATE":"B",
   "CSBTSTREET1":"Tierra del Fuego 1481",
   "CSSTSTREET1":"Tierra del Fuego 1481",
   "CSBTCUSTOMERID":"2927",
   "CSBTIPADDRESS":"200.126.204.34",
   "CSPTCURRENCY":"ARS",
   "CSPTGRANDTOTALAMOUNT":"47.25",
   "CSMDD7":"",
   "CSMDD8":"Y",
   "CSMDD9":"",
   "CSMDD10":"",
   "CSMDD11":"",
   "CSMDD12":"",
   "CSMDD13":"",
   "CSMDD14":"",
   "CSMDD15":"",
   "CSMDD16":"",
   "CSITPRODUCTCODE":"electronic_good",
   "CSITPRODUCTDESCRIPTION":"VOUCHER",
   "CSITPRODUCTNAME":"VOUCHER",
   "CSITPRODUCTSKU":"VOUCHER",
   "CSITTOTALAMOUNT":"47.25",
   "CSITQUANTITY":"1",
   "CSITUNITPRICE":"47.25"
}

# y la respuesta:

`{
   "Operations":{
      "RESULTCODE":"99978",
      "RESULTMESSAGE":"Tu compra no pudo realizarse. Iniciala nuevamente utilizando otro medio de pago.",
      "DATETIME":"2018-02-10T18:36:01.123-03:00",
      "OPERATIONID":"1518298555-2927-443-633-1-8",
      "CURRENCYCODE":"32",
      "AMOUNT":"47.25",
      "FEEAMOUNT":{
         "@attributes":{
            "nil":"true"
         }
      },
      "TAXAMOUNT":{
         "@attributes":{
            "nil":"true"
         }
      },
      "SERVICECHARGEAMOUNT":{
         "@attributes":{
            "nil":"true"
         }
      },
      "CREDITEDAMOUNT":"47.25",
      "AMOUNTBUYER":"47.25",
      "FEEAMOUNTBUYER":{
         "@attributes":{
            "nil":"true"
         }
      },
      "TAXAMOUNTBUYER":{
         "@attributes":{
            "nil":"true"
         }
      },
      "BANKID":"7",
      "PROMOTIONID":"1684425",
      "TYPE":"compra_online",
      "INSTALLMENTPAYMENTS":"1",
      "CUSTOMEREMAIL":"XXX@hotmail.com",
      "IDENTIFICATIONTYPE":"DNI",
      "IDENTIFICATION":"XXXXXXXX",
      "CARDNUMBER":"4540XXXXXXX1518",
      "CARDHOLDERNAME":"XXXXXXXX XXXXXXX",
      "TICKETNUMBER":"0",
      "AUTHORIZATIONCODE":{
         "@attributes":{
            "nil":"true"
         }
      },
      "BARCODE":{
         "@attributes":{
            "nil":"true"
         }
      },
      "COUPONEXPDATE":{
         "@attributes":{
            "nil":"true"
         }
      },
      "COUPONSECEXPDATE":{
         "@attributes":{
            "nil":"true"
         }
      },
      "COUPONSUBSCRIBER":{
         "@attributes":{
            "nil":"true"
         }
      },
      "PAYMENTMETHODCODE":"42",
      "PAYMENTMETHODNAME":"VISA",
      "PAYMENTMETHODTYPE":"Cru00e9dito",
      "OPERATIONNUMBER":"30113014",
      "AUTHORIZATIONKEY":"eb02bb6b-d194-430b-b4e5-402e08034597",
      "REFUNDED":{
         "@attributes":{
            "nil":"true"
         }
      },
      "PUSHNOTIFYMETHOD":{
         "@attributes":{
            "nil":"true"
         }
      },
      "PUSHNOTIFYENDPOINT":{
         "@attributes":{
            "nil":"true"
         }
      },
      "PUSHNOTIFYSTATES":{
         "@attributes":{
            "nil":"true"
         }
      },
      "IDCONTRACARGO":"0",
      "FECHANOTIFICACIONCUENTA":{
         "@attributes":{
            "nil":"true"
         }
      },
      "ESTADOCONTRACARGO":{
         "@attributes":{
            "nil":"true"
         }
      },
      "COMISION":{
         "@attributes":{
            "nil":"true"
         }
      },
      "CFT":"0.00",
      "TEA":"0.00",
      "RELEASESTATUS":"TX_RECHAZADA",
      "RELEASEDATETIME":{
         "@attributes":{
            "nil":"true"
         }
      },
      "REFUNDS":[

      ],
      "PHONENUMBER":"542915091865",
      "ADDRESS":"Tierra del Fuego 1481",
      "POSTALCODE":"8000",
      "CUSTOMERID":"2927",
      "ITEMS":{
         "ITEM":{
            "code":"electronic_good",
            "description":"VOUCHER",
            "name":"VOUCHER",
            "price":"47.25",
            "quantity":"1",
            "sku":"VOUCHER",
            "totalAmount":"47.25"
         }
      }
   }
}`
Los nombres, el dni, y correos estan bien cargados y corresponden.
Desde ya muchas gracias

**Comment by bpieres** [comment]
Mismo Error, pero no dan respuesta.

**Comment by gonzalojmartin** [comment]
Hace unos días estoy teniendo el mismo inconveniente. Y en 0800 nada sabe nada.
Ejemplo:

Array ( [StatusCode] => 99979 [StatusMessage] => Tu compra no pudo realizarse. Iniciala nuevamente utilizando otro medio de pago. [AuthorizationKey] => 6cfb64f3-758a-41a7-a8db-89b29e062078 [EncodingMethod] => XML [Payload] => Array ( [Answer] => Array ( [DATETIME] => 2019-02-07T12:38:00 -0300 [CURRENCYNAME] => Peso Argentino [PAYMENTMETHODNAME] => VISA [TICKETNUMBER] => 6981 [AUTHORIZATIONCODE] => 001453 [CARDNUMBERVISIBLE] => 4593XXXXXXXX6949 [BARCODE] => [OPERATIONID] => 90 [COUPONEXPDATE] => [COUPONSECEXPDATE] => [COUPONSUBSCRIBER] => [BARCODETYPE] => [ASSOCIATEDDOCUMENTATION] => [INSTALLMENTPAYMENTS] => 1 [OPERATIONNUMBER] => 34630016 [CFT] => 0.0000 [TEA] => 0.0000 ) [Request] => Array ( [MERCHANT] => 1423295 [OPERATIONID] => 90 [AMOUNT] => 742.50 [CURRENCYCODE] => 32 [AMOUNTBUYER] => 742.50 [BANKID] => 17 [PROMOTIONID] => 2121107 ) ) )

**Comment by santiagosgr** [comment]
@gonzalojmartin Te recomiendo que mandes por Messenger a TodoPago, ahí por lo menos te especifican un poco más a qué se debe el error.

**Comment by gonzalojmartin** [comment]
@santiagosgr a que usuario de Messenger?? Gracias!

**Comment by santiagosgr** [comment]
@gonzalojmartin TodoPagoAr

**Comment by faculezcano** [comment]
Hola, probando varias cosas noté que el rebote de estos pagos sin error disminuye si se envian mas datos del cliente (telefono, dni, direccion) que por lo visto algunos bancos como medida de seguridad verifican mas datos y todo pago deficientemente no especifica bien los errores. De todas formas los rebotes siguieron, en menor medida y tome la medida de cambiar de medio de pago(MP) en mi plataforma. Espero que les sirva de algo

**Comment by curcio79** [comment]
Nos disculpamos por la demora en la respuesta y lamentamos mucho que hayas tenido este inconveniente. Si necesitás ayuda, llamanos al  0800-333-0010 o escribinos a contacto@todopago.com.ar
