### ISSUE TITLE
sendAutorizeRequest devuelve StatusCode null

### ISSUE THREAD

**Issue by faculezcano** [TodoPago/SDK-PHP#45]
Hola que tal, a partir de hoy temprano el servicio empezo a devolver la respuesta de sendAutorizeRequest vacio

{"StatusCode":null,"StatusMessage":"","URL_Request":"","RequestKey":"","PublicRequestKey":""}

Cual es el problema?

## Requisitos

[X] ¿Habilitaste la extensión SOAP de PHP?
[X] ¿Habilitaste la extensión CURL de PHP?
[X] ¿Habilitaste la extensión openSSL de PHP?
[X] ¿Seguiste los pasos de instalación descritos en [README.md](https://github.com/TodoPago/dev-sdk-php/blob/master/README.md)?

## Comportamiento esperado
StatusCode con codigo de error o aprobada

## Comportamiento actual
StatusCode = null

## Pasos a reproducir
Realizar la guia de github hasta sendAutorizeRequest()

## Entorno
> Completar con las versiones de las distintas herramientas aplicadas.
+ Entorno
  * Linux
  * Apache
  * PHP 7.1
  * SDK 1.10.2

**Comment by giovaniferrarotrivelli** [comment]
Mismo problema por acá. El problema empezó a suceder de manera repentina el día de ayer.

**Comment by drarko** [comment]
Buenas tardes estimados,
Por favor, podrian indicarnos sus Merchant para realizar el analisis correspondiente?
Muchas gracias

**Comment by giovaniferrarotrivelli** [comment]
106708, gracias por la pronta respuesta (hoy temprano me comuniqué con soporte y ni bola).

**Comment by faculezcano** [comment]
Yo igual me comunique por todos los medios posibles antes de abrir el issue y no bola

**Comment by diernan** [comment]
Mismo problema MerchantId 35261

**Comment by faculezcano** [comment]
Son un desastre muchachos, no tienen un canal de comunicación para desarrolladores, no contestan nunca. Van a hacer una actualización, que rompió todo, y no avisan. Tienen códigos de error misteriosos que no quieren dar información para intentar de mitigarlos (99979,99979), muy poco serio.

**Comment by faculezcano** [comment]
Cuando implementaron pago con efectivo, lo habilitaron por defecto, hay varios que con la URL de éxito se verifica el pago y si es aprobado se adjudica el producto, el pago por efectivo daba código aprobado antes de que la gente vaya a rapipago/pagofacil a pagar. Esto resultó en productos entregados sin que la gente los pague. Catastrófico, no se entiende el criterio que tienen.

**Comment by faculezcano** [comment]
Hoy acaba de volver a pasar, no se puede creer

**Comment by giovaniferrarotrivelli** [comment]
En estos momentos directamente no conecta al servidor de TodoPago. Necesito obtener los pagos con $client->getByRangeDateTime y queda cargando indefinidamente...

**Comment by Mozo-Dev** [comment]
Hola!. Tengo el mismo inconveniente. Es por la version de PHP 7.1?. Mi numero de merchant es 110813.
Gracias.

**Comment by GiovaniFerraroTrivelli** [comment]
@Mozo-Dev yo me cambié a MercadoPago. Estaba perdiendo muchos clientes con TodoPago teniendo errores de este estilo.
La verdad que un desastre,

**Comment by Mozo-Dev** [comment]
Es una lastima. Lo unico que vi es que la request soap como curl tira timeout 504.

**Comment by Mozo-Dev** [comment]
Bueno arregle mi problema. En mi caso era que el CSBTCUSTOMERID no podia contener espacios.
Así que use una expresión regular para sacárselos y funciono perfecto.
> preg_replace('/\s+/', '_',$customerID)

Espero ayudar a otros con esta explicación.

**Comment by faculezcano** [comment]
> @Mozo-Dev yo me cambié a MercadoPago. Estaba perdiendo muchos clientes con TodoPago teniendo errores de este estilo.
> La verdad que un desastre,

Yo hace rato opte por lo mismo, es malisimo TP

**Comment by DEV7163** [comment]
Tengo el mismo problema.
Se supone que aún funciona el SDK al día de hoy?

**Comment by curcio79** [comment]
@DEV7163 si funciona, generame un nuevo ticket y lo seguimos desde ahi, te parece?
