### ISSUE TITLE
Integracion whmcs

### ISSUE THREAD

**Issue by sipgatenetworks** [TodoPago/SDK-PHP#46]
Alguien ha podido integrar Todo Pago con WHMCS ?
No logro integrarlo y mucho menos con Callback.

Alguien puede proporcionar el modo de integrarlo correctamente ?

**Comment by jonyalbelo** [comment]
Hola. Pudiste conseguir algo? Gracias

**Comment by sipgatenetworks** [comment]
Hola, no, lamentablemente nada de nada. Intente buscar también para Pay U argentina y tampoco hay nada.
Uso actualmente  Cuenta Digital, pero tiene mil vueltas, te matan con las comisiones ,liberan los fondos en 30 dias habiles. y si cobras en Dolares USA la tasa de conversión es abusiva (para que te des una idea, mientras en el mercado oficial estaba u$s 1,00 = $ 28  ellos convertían **a la fuerza** a razon de U$S.1,00 = $ 15 ). Un disparate
