### ISSUE TITLE
Error "98001 	ERROR: El campo CSBTCITY es requerido"

### ISSUE THREAD

**Issue by matijdk** [TodoPago/SDK-PHP#48]
# SDK-PHP | Issue Técnico
> Poner un problema en su respectivo contexto acelera su resolución. </br>
Esta guía tiene como objetivo contextualizar el inconveniente desde un primer momento.

> __Para consultas acerca de nuevas funcionalidades o información comercial utiliza el formulario de contacto de www.todopago.com.ar__

## Requisitos

* [ ] ¿Habilitaste la extensión SOAP de PHP?
* [ ] ¿Habilitaste la extensión CURL de PHP?
* [x] ¿Habilitaste la extensión openSSL de PHP?
* [x] ¿Seguiste los pasos de instalación descritos en [README.md](https://github.com/TodoPago/dev-sdk-php/blob/master/README.md)?
* [x] Completar con una X dentro de los corchetes para los requisitos cumplidos.

## Comportamiento esperado
> Describinos qué respuesta se espera.

## Comportamiento actual
> Describinos qué está sucediendo actualmente.

## Pasos a reproducir
> Contanos, con el mayor detalle posible, qué pasos realizar para replicar el error.

## Entorno
> Completar con las versiones de las distintas herramientas aplicadas.
+ Entorno
  * __SO:__
  * __Servidor Web y versión:__
  * __Versión de PHP:__ _De ser posible, link a phpinfo()_
  * __Versión de SDK:__
  * __Ambiente de Todopago:__

## Comentario
> Cualquier cosa que quieras comentas que consideres pueda aportar a la detección y resolución del problema.
Hola! Tengo un problema.
Uso woocommerce, y tengo ya funcionando mi pagina.
Tengo la ultima version del modulo de todo pago, y me esta dando un error:

"Error en: Autorización El campo CSBTCITY es obligatorio. (Minlength 2)"

Alguien podria decirme como sacarlo? Yo no recibia este error antes, luego cambie unas cuestiones en wordpress, fui a modificar el functions.php del tema de woocommerce solo para que no le pida al comprador antes de finalizar la compra los datos de envio y los suyos otra vez. 

Luego de esto comenzo con el error el modulo! Yo pense que el error viene por el lado de que el modulo me pide como obligatoro ese campo que muestra el error "CSBTCITY " (que no se que es) y yo al "anularlo" en woocommerce el modulo no termina de realizar la aprobacion para la compra! 

De ser asi.... que podria hacer para solucionarlo? Para modificar en el modulo que ese campo CSBTCITY no sea obligatorio???

Lo que cambie fue:

add_filter( 'woocommerce_checkout_fields' , 'custom_override_checkout_fields' );
 
function custom_override_checkout_fields( $fields ) {
    unset($fields['billing']['billing_first_name']);
    unset($fields['billing']['billing_last_name']);
    unset($fields['billing']['billing_company']);
    unset($fields['billing']['billing_address_1']);
    unset($fields['billing']['billing_address_2']);
    unset($fields['billing']['billing_city']);
    unset($fields['billing']['billing_postcode']);
    unset($fields['billing']['billing_country']);
    unset($fields['billing']['billing_state']);
    unset($fields['billing']['billing_phone']);
    unset($fields['order']['order_comments']);
    unset($fields['billing']['billing_address_2']);
    unset($fields['billing']['billing_postcode']);
    unset($fields['billing']['billing_company']);
    unset($fields['billing']['billing_last_name']);
    unset($fields['billing']['billing_email']);
    unset($fields['billing']['billing_city']);
    unset($fields['shipping']['shipping_city']);
    unset($fields['shipping']['shipping_first_name']);
    unset($fields['shipping']['shipping_last_name']);
    unset($fields['shipping']['shipping_company']);
    unset($fields['shipping']['shipping_address_1']);
    unset($fields['shipping']['shipping_address_2']);
    unset($fields['shipping']['shipping_postcode']);
    unset($fields['shipping']['shipping_country']);
    unset($fields['shipping']['shipping_state']);
    unset($fields['shipping']['shipping_phone']);
    return $fields;
}

Muchisimas gracias al que pueda ayudarme! Saludos!

**Comment by monpac** [comment]
Al realizar una compra por TodoPago, se piden los datos del comprador por temas de fraude. De esta manera lo que hiciste fue sacarlos y el plugin está fallando porque requiere estos campos. Al menos que pongas datos por default (que no lo recomiendo) no vas a poder sacar estos campos. Fijate en el readme está definido lo que es el campo "CSBTCITY" que basicamente sería el "Customer Billing City"

**Comment by dafonk** [comment]
Realmente esto significa que para integrar esta forma de pago tengo que poner toooodos los campos que da como requeridos.... eso es inaceptable. No se puede obligar al cliente a escribir una biblia para realizar una simple compra... realmente no hay forma de poner esos campos como No requeridos...? Si es así no se puede usar....

**Comment by dafonk** [comment]
Si pero esto debería ir por un formulario externo, para los que se conocen con esta forma de pago y no obligarnos a los comerciantes a poner todos esos campos en nuestro formulario, es decir que nuestros clientes tengan que llenar todos esos campos también con las otras formas de pago....

Igualmente gracias por la respuesta
