### ISSUE TITLE
Instalacion manual y funcionalidad de notificacion asincronica

### ISSUE THREAD

**Issue by diegolaz** [TodoPago/SDK-PHP#52]
Hola! Queria saber si para la instalacion manual solo se necesita el archivo Sdk.php o todo el contenido de la carpeta vendor ([aca ](https://developers.todopago.com.ar/site/php) dice solo el file TodoPago.php pero creo debe ser viejo porque ni existe el archivo ese)

Una vez funcionando... exite la funcionalidad de notificaciones IPN que utilizan PayPal y MP o como se trata el caso en que el cliente cierre el browser o algo asi luego de hacer el pago?

Gracias!

**Comment by curcio79** [comment]
@diegolaz buenos dias, deberias colocar todos los archivos, no solo el sdk.php. Lo que si podrias evitar la carpeta 
/resources ya que en la misma estan los ejemplos de uso.

Con relacion a las notificaciones IPN, no hay disponible nada
