### ISSUE TITLE
No ofrece la cantidad de cuotas enviadas como parámetro

### ISSUE THREAD

**Issue by diernan** [TodoPago/SDK-PHP#53]
# SDK-PHP | Issue Técnico
> Poner un problema en su respectivo contexto acelera su resolución. </br>
Esta guía tiene como objetivo contextualizar el inconveniente desde un primer momento.

> __Para consultas acerca de nuevas funcionalidades o información comercial utiliza el formulario de contacto de www.todopago.com.ar__

## Requisitos

* [ x] ¿Habilitaste la extensión SOAP de PHP?
* [ x] ¿Habilitaste la extensión CURL de PHP?
* [ x] ¿Habilitaste la extensión openSSL de PHP?
* [ x] ¿Seguiste los pasos de instalación descritos en [README.md](https://github.com/TodoPago/dev-sdk-php/blob/master/README.md)?
* [x] Completar con una X dentro de los corchetes para los requisitos cumplidos.

## Comportamiento esperado
> Al enviar MAXINSTALLMENTS = XX esperamos que nos muestre todas las opciones de cuotas hasta XX que ofrece su plataforma

## Comportamiento actual
> Solo muestra la opción de 1 cuota
## Pasos a reproducir
>Eviamos los parámetros tal cual como lo indican ustedes.

## Entorno
> Completar con las versiones de las distintas herramientas aplicadas.
+ Entorno
  * __SO:__LINUX
  * __Servidor Web y versión:__Todos los sitios en los que tenemos implementado todopago
  * __Versión de PHP:__ _De ser posible, link a phpinfo()_
  * __Versión de SDK:__1.1
  * __Ambiente de Todopago:__Produccion

## Comentario
> Cualquier cosa que quieras comentas que consideres pueda aportar a la detección y resolución del problema.
Ayer en varias respuesta del second_step aprobadas devolvió STATUS:"null". Hoy tenemos este problema.

**Comment by marcosvolpiok** [comment]
@diernan te solicito más información para poder detectar mejor el problema:
-¿Estás usando el formulario externo o el híbrido?
-¿Podrás facilitarme los datos enviados en el SAR?


Saludos.
