### ISSUE TITLE
Consulta de Medios de Pago

### ISSUE THREAD

**Issue by leonarpv** [TodoPago/SDK-PHP#54]
Hola Una simple consulta con respecto a los id de medios de pago
1, 42 y 500 hacen referencia a cuales medios de pago especificamente?

> 'AVAILABLEPAYMENTMETHODSIDS'=>"1#42#500"

**Comment by monpac** [comment]
@leonarpv probá este request https://github.com/TodoPago/SDK-PHP#discover

Este es el código que debería de darte los métodos de pagos habilitados en la cuenta:

`
$client = new TodoPago\Sdk($http_header, $mode);
$rta = $client->discoverPaymentMethods();
`
