### ISSUE TITLE
refused to display in a frame because it set 'x-frame-options' to 'sameorigin'

### ISSUE THREAD

**Issue by bpieres** [TodoPago/SDK-PHP#55]
Estoy recibiendo este error cuando envío los datos para procesar el pago. 

Alguna idea?

Gracias

![errortest](https://user-images.githubusercontent.com/5640374/44290669-25cbd980-a250-11e8-91c1-2dc4647a1da1.png)

**Comment by bpieres** [comment]
@todo-pago Estimados, necesitamos ayuda con este issue. Muchas gracias

**Comment by curcio79** [comment]
@bpieres buenos dias, estabas implementando el formulario de pago dentro de un iframe, puede ser?
