### ISSUE TITLE
Error ejecutando en modo test el sdk

### ISSUE THREAD

**Issue by dsurra** [TodoPago/SDK-PHP#56]
# SDK-PHP | Issue Técnico
> Poner un problema en su respectivo contexto acelera su resolución. </br>
Esta guía tiene como objetivo contextualizar el inconveniente desde un primer momento.

> __Para consultas acerca de nuevas funcionalidades o información comercial utiliza el formulario de contacto de www.todopago.com.ar__

## Requisitos

* [x] ¿Habilitaste la extensión SOAP de PHP?
* [x] ¿Habilitaste la extensión CURL de PHP?
* [x] ¿Habilitaste la extensión openSSL de PHP?
* [x] ¿Seguiste los pasos de instalación descritos en [README.md](https://github.com/TodoPago/dev-sdk-php/blob/master/README.md)?
* [x] Completar con una X dentro de los corchetes para los requisitos cumplidos.

## Comportamiento esperado
> Debería ejecutar el código llamando al metodo getStatus pero tira Timeout.

## Comportamiento actual
> Debería ejecutar el código llamando al metodo getStatus pero tira t.

## Pasos a reproducir
> Al recibir el success url intento buscar el resultado en el array con Operations pero da Timeout.

## Entorno
> Completar con las versiones de las distintas herramientas aplicadas.
+ Entorno
  * __SO: Ubuntu 14.04
  * __Servidor Web y versión: nginx
  * __Versión de PHP: php 7.1
  * __Versión de SDK: 1.10.2
  * __Ambiente de Todopago: Test

## Comentario
> Mensaje de error en un browser haciendo el get.

Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /services/t/1.1/api/Operations/GetByOperationId/MERCHANT/2159/OPERATIONID/5b6061ea4d76b.

Reason: Error reading from remote server

![seleccion_131](https://user-images.githubusercontent.com/16765646/43463309-a86636ce-94ae-11e8-972f-61d92081e307.png)

**Comment by curcio79** [comment]
@dsurra nos disculpamos por la demora en la respuesta y lamentamos mucho que hayas tenido este inconveniente. Si necesitás ayuda, llamanos al  0800-333-0010 o escribinos a contacto@todopago.com.ar
