### ISSUE TITLE
Proceso de Pago dentro de Iframe

### ISSUE THREAD

**Issue by andrespar** [TodoPago/SDK-PHP#57]
Hola, estoy implementando la pasarela de pago dentro de un sitio embebido en un iframe, al momento de realizar el redireccionamiento me muestra una serie de errores y no termina de renderizar el formulario de Pago.
En tal caso, les consulto. 

Es por seguridad de la pasarela de pago?

En tal caso se podría utilizar la pasarela desde un popUp ?

Gracias

**Comment by curcio79** [comment]
@andrespar depende si estas usando la opcion hibrida o la opcion redireccionamiento. Con la hibrida no creo q tengas problema de usar la version popup. Saludos
