### ISSUE TITLE
Error -999 "Ha ocurrido un error inesperado"

### ISSUE THREAD

**Issue by hardkito** [TodoPago/SDK-PHP#59]
# SDK-PHP | Issue Técnico
Hace 2 años aproximadamente está funcionando la integración correctamente. 
Ahora han reportado varios clientes que reciben el siguiente error:

-999 "Ha ocurrido un error inesperado"

Se produce al momento de postear el formulario de pago, luego de escoger y completar todos los parámetros del pago (datos de tarjeta, etc.). No le pasa a todos, es decir que sucede en algunos casos.
¿A que se debe?

Aclaro que no es un mensaje del ecommerce sino que es uno que devuelve la API de TodoPago directamente.

Gracias.
Saludos!

Leonel

**Comment by braianjchristiansen** [comment]
Buenas,
Estoy implementando el formulario hibrido en mi sitio. Me sucede lo mismo que estan describiendo.
Lo increible es que el pago se acredita, pero me devuelve mensaje -999 "Ha ocurrido un error inesperado". Solo pasa cuando se paga con saldo virtual. Si pago con tarjeta, todo ok.
Pudieron solucionar este problema? Agradecere que me indiquen como, en caso de haberlo hecho.
Gracias

**Comment by curcio79** [comment]
@hardkito  Nos disculpamos por la demora en la respuesta y lamentamos mucho que hayas tenido este inconveniente. Si necesitás ayuda para volver a implementarlo escribime, llamanos al  0800-333-0010 o escribinos a contacto@todopago.com.ar. @braianjchristiansen sigo con vos en tu issue, te parece?
