### ISSUE TITLE
Actualizando SDK y JS endpoints para formulario híbrido: no se cargan los selects

### ISSUE THREAD

**Issue by hardkito** [TodoPago/SDK-PHP#61]
# SDK-PHP | Issue Técnico
> Actualizando SDK y JS endpoints para formulario híbrido no se cargan las opciones de cada select:
Medio de pago
Banco
Cuotas

Ni tampoco devuelve error. 

## Requisitos

* [x ] ¿Habilitaste la extensión SOAP de PHP?
* [x] ¿Habilitaste la extensión CURL de PHP?
* [x] ¿Habilitaste la extensión openSSL de PHP?
* [x] ¿Seguiste los pasos de instalación descritos en [README.md](https://github.com/TodoPago/dev-sdk-php/blob/master/README.md)?

## Comportamiento esperado
> Carga automática de selects en formulario híbrido

## Comportamiento actual
> Se carga solo la opción que da nombre a cada select (Medio de pago, Banco, Cuotas)

## Pasos a reproducir
> Con solo cargar el formulario híbrido en entorno desarrolo.

## Entorno
> Completar con las versiones de las distintas herramientas aplicadas.
+ Entorno
  * __SO: Linuz
  * __Servidor Web y versión: Apache 2
  * __Versión de PHP: 5.6
  * __Versión de SDK:1.10.2
  * __Ambiente de Todopago:Desarrollo con endpoint: https://developers.todopago.com.ar/resources/v2/TPBSAForm.min.js

## Comentario
> Los campos solicitados por el script son otros en relación al ejemplo de formulario híbrido que se puede ver en esta documentación en GitHub. Los modifiqué y agregue otros de tipo Lbl (label). 

Ejemplo de cambio: 
 antes: formaDePagoCbx
 ahora: formaPagoCbx

**Comment by curcio79** [comment]
@hardkito te puedo ayudar en algo con esta implementacion?
