### ISSUE TITLE
Problemas captura callback Form Hibrido JS

### ISSUE THREAD

**Issue by tatunga23** [TodoPago/SDK-PHP#62]
Estimados buenas tardes,

Nuestra plataforma esta utilizando satisfactoriamente desde hace un tiempo a la fecha el Form Hibrido de JS, pero estamos teniendo muchos casos donde no llegamos a capturar el callback del boton de pago, no sabemos si es por Time Out, cortes o algun otro motivo.
Les consultamos si nos pueden ayudar detallando posibles casos de error comunes que debemos contemplar, Time Out sugeridos para callback del boton de pago, contingencias para diferentes casos.

Aguardamos su pronta respuesta desde ya muchas gracias!
Slds.,

Leandro

**Comment by curcio79** [comment]
@tatunga23 Buenos dias, pudiste resolver el problema? hay algo en lo cual te pueda ayudar?
