### ISSUE TITLE
Problema con método getStatus

### ISSUE THREAD

**Issue by lucianoghione** [TodoPago/SDK-PHP#63]
Hola, el método getStatus me devuelve un array vacio, hay alguna manera de evitar usar el método getAuthorizeAnswer? Ya que necesita el AnswerKey y si existe algún problema al regresar al sitio desde todopago se pierde la transacción.

**Comment by monpac** [comment]
@lucianoghione que key le estás enviando al getStatus? Fijate que sea el mismo ticket de operación que le enviaste al generar el pago.

**Comment by lucianoghione** [comment]
> @lucianoghione que key le estás enviando al getStatus? Fijate que sea el mismo ticket de operación que le enviaste al generar el pago.

Hola! Gracias por responder, le estoy pasando el OPERATIONID que le pase al método sendAuthorizeRequest() y el MERCHANT le puse el Merchant ID (modo sandbox) que te da todopago, cabe destacar que estoy en modo de pruebas y no lo he probado en modo producción.

**Comment by monpac** [comment]
El modo que le estás enviando me imagino entonces que también lo tenés en modo Sandbox entonces no? En desarrollo nunca lo probé pero en producción y enviando ambos Merchant y Operation ID funcionó siempre. Fijate quizá es eso.

**Comment by Marche86** [comment]
A mi me comenzó a pasar lo mismo... Funciona perfecto.

**Comment by curcio79** [comment]
@lucianoghione  nos disculpamos por la demora en la respuesta y lamentamos mucho que hayas tenido este inconveniente. Si necesitás ayuda, llamanos al 0800-333-0010 o escribinos a contacto@todopago.com.ar o escribime a mi
