### ISSUE TITLE
Problema para devolver pago voidRequest()

### ISSUE THREAD

**Issue by lucianoghione** [TodoPago/SDK-PHP#64]
Hola, tengo un problema al intentar hacer una devolución total en entorno de prueba. El SDK PHP me devuelve:
Cabe destacar que según la documentación no es necesario enviar el campo AMOUNT.
También probe intentando hacer una devolución parcial y el error es el mismo.

Respuesta del SDK:
array(4) {
  ["StatusCode"]=>
  int(1016)
  ["StatusMessage"]=>
  string(32) "El monto ingresado es inválido."
  ["AuthorizationKey"]=>
  string(36) "8c8cb8da-aebc-4ea7-1fba-c93e6d9a514c"
  ["AUTHORIZATIONCODE"]=>
  string(0) ""
}

Saludos

**Comment by curcio79** [comment]
@lucianoghione buenos dias y perdon por la tardanza en la respuesta. Como bien vos decis, no es requerido el campo AMOUNT a mas que hagas una devolucion parcial. Con una version posterior, pudiste hacer la devolucion sin problemas? Te puedo ayudar en algo?
