### ISSUE TITLE
Consulta WebService

### ISSUE THREAD

**Issue by solatur** [TodoPago/SDK-PHP#66]
Estoy armando una aplicación en php, solo necesito saber los precios:
https://todopago.com.ar/precios
Existe algun web service donde solamente se pueda consultar esto?
Actualmente con mercadopago recurro a la api de mercado pago que me trae estos datos...solo necesito saber los precios en linea...
todo pago tiene un web service con esta info?
Desde ya muchas gracias.
Mario

# SDK-PHP | Issue Técnico
> Poner un problema en su respectivo contexto acelera su resolución. </br>
Esta guía tiene como objetivo contextualizar el inconveniente desde un primer momento.

> __Para consultas acerca de nuevas funcionalidades o información comercial utiliza el formulario de contacto de www.todopago.com.ar__

## Requisitos

* [ ] ¿Habilitaste la extensión SOAP de PHP?
* [ ] ¿Habilitaste la extensión CURL de PHP?
* [ ] ¿Habilitaste la extensión openSSL de PHP?
* [ ] ¿Seguiste los pasos de instalación descritos en [README.md](https://github.com/TodoPago/dev-sdk-php/blob/master/README.md)?
* [x] Completar con una X dentro de los corchetes para los requisitos cumplidos.

## Comportamiento esperado
> Describinos qué respuesta se espera.

## Comportamiento actual
> Describinos qué está sucediendo actualmente.

## Pasos a reproducir
> Contanos, con el mayor detalle posible, qué pasos realizar para replicar el error.

## Entorno
> Completar con las versiones de las distintas herramientas aplicadas.
+ Entorno
  * __SO:__
  * __Servidor Web y versión:__
  * __Versión de PHP:__ _De ser posible, link a phpinfo()_
  * __Versión de SDK:__
  * __Ambiente de Todopago:__

## Comentario
> Cualquier cosa que quieras comentas que consideres pueda aportar a la detección y resolución del problema.

**Comment by curcio79** [comment]
@solatur buenos dias, todavia no tenemos habilitado ningun WS de ese estilo
