### ISSUE TITLE
PAGO RECHAZADO

### ISSUE THREAD

**Issue by rakshaka** [TodoPago/SDK-PHP#67]
Estoy utilizando la prueba por medio de PHP... utilizo el ejemplo_1 que se encuentra en las carpetas que ustedes facilitan. Lleno los campos y puse para el entorno de prueba.
Me deja pasar a TODOPAGO a la plataforma de pago con tarjeta. Allí lleno los datos con las tarjetas de test que facilitan ustedes. Pero al finalizar me da el pago como rechazado siempre. Como puedo solucionar esto?

**Comment by hernancastro20** [comment]
Hola @rakshaka, a mi me pasa lo mismo, y no se que tocar ya, tenes idea de que puede ser si es que lo solucionaste?
mil gracias

**Comment by mgomenzoro** [comment]
Buenas, me pasa exactamente lo mismo.  LLego hasta el formulario, completo los datos con la tarjeta de credito pero siempre me devuelve a la página de error.  Cuando voy al panel de administracion de mi cuenta en la web de todo pago el motivo de rechazo es siempre el mismo:"La compra no pudo realizarse. Informale a tu comprador que utilice otro medio de pago."  No sé qué hacer.  Me comuniqué 2 veces con atención al cliente y me dicen que ese error es porque la entidad financiera rechazó el pago... pero a mi no me parece.

**Comment by hernancastro20** [comment]
Hola @mgomenzoro : te cuento lo que hice yo que ya realicé varios pagos exitosos....
1ro ejecutalo directamente en el hosting, 
2do ejecutalo en modo PRODUCCIÓN, EL MODO TEST NUNCA FUNCIONÓ. 
3ro SOLO MODIFICÁ el **Authorization, merchant, security, y el modo a prod.** (y si queres el precio en el html, yo lo probé con $20, ojo con esto, si hay algo mal tampoco va a andar, sino la primera vez dejalo como está)
probalo así sin tocar mas por ahora. 
si funciona así despues lo pones como querés. SUERTE!

**Comment by rakshaka** [comment]
Olvidate, nadie contesta

**Comment by mgomenzoro** [comment]
Hola hernan! gracias por responder, te cuento que tengo todo en el servidor, estoy en produccion, y modifiqué lo mínimo y necesario, tal como vos decís y no hay caso ! es mas, algunas operaciones fueron aprobadas cuando hacía todo localmente (en producción), y al copiar el mismo archivo al server me rechazaba las operaciones ! de no creer, comienzo a creer que es un problema de TP... si no cómo me explicás que localmente me funcionó y el mismo archivo subido al server no? obviamente volví a probar localmente y como era de esperarse, esta vez no funcionó.  Para colmo necesito TP para ofrecer ahora12, ya que mi rubro lo permite.  Uso también mercadopago, funciona perfecto pero no da ahora 12.

**Comment by hernancastro20** [comment]
@mgomenzoro , de nada! 
probá si queres meterte en TP y regenerate las credenciales. 
yo te digo que ni hasta las urls cambié, si renombré el archivo no, obvio. 
a mi me anda solo modificando lo que te dije inicialmente y bueno ahora paso el array que necesito y va bien. 
pero di un montón de vueltas, es terrible...

**Comment by mgomenzoro** [comment]
Buenas noticias! regeneré las credenciales como lo sugirió @hernancastro20 y comenzó a funcionar ! Gracias a todos por la ayuda!

**Comment by hernancastro20** [comment]
excelente! disfrutalo! saludos!

**Comment by rakshaka** [comment]
Lo voy a probar!!!

**Comment by mgomenzoro** [comment]
jajaj duró poco muchachos la satisfacción.  Hoy volví a probar y volvimos a los pagos rechazados.  Volví a regenerar las credenciales pero siguieron siendo rechazados los pagos.... me rindo

**Comment by rakshaka** [comment]
Es un desastre la API... limita mucho. DATO, la de todopago va como piña,

**Comment by mgomenzoro** [comment]
Bueno, algo nuevo, contestaron mi reclamo después de casi una semana, con un simple texto: " Le pedimos que intente realizar la operación nuevamente. 
Saludos.
Equipo Todo Pago"
Luego de recibir este mail, volví a probar y funcionó.  Además noté otra cosa en el formulario de checkout, ahora aparece el logo de mi empresa, cosa que antes no aparecía a pesar de que yo lo había subido desde el panel de administración de TP.  A partir de este momento he realizado dos operaciones y por suerte (y toco madera) fueron aprobadas!
La semana que viene seguiré probando y si todo sale bien y sigue funcionando les confirmaré por este medio.
Saludos !

**Comment by curcio79** [comment]
@mgomenzoro te hago una consulta, te siguio funcionando?
