### ISSUE TITLE
Cómo generar un formulario para un cliente que no sea de Argentina

### ISSUE THREAD

**Issue by mmondino** [TodoPago/SDK-PHP#68]
# SDK-PHP | Issue Técnico

¿ Cómo generar un formulario para un cliente que no sea de Argentina ?

El api exige que se especifique provincia Argentina.

**Comment by sebaherrera** [comment]
Parece que no hay nadie de Todo Pago dispuesto a resolver las cuestiones más básicas. 

Sólo podés cobrarle a argentinos. Para clientes de afuera, tenés que usar Paypal o similares.

**Comment by bpieres** [comment]
Son de terror...

**Comment by curcio79** [comment]
Hola @mmondino nos disculpamos por la demora en la respuesta. Por favor, llamanos al 0800-333-0010 o escribinos a contacto@todopago.com.ar para que te ayudemos a resolverlo.
