### ISSUE TITLE
[Error] Ha habido un error. Por favor inténtelo de nuevo. Error 98104

### ISSUE THREAD

**Issue by fcaivano** [TodoPago/SDK-PHP#7]
Hola,

El siguiente error devuelto:

> Ha habido un error. Por favor inténtelo de nuevo. Error 98104

No esta documentado. Saben a que se debe?

No cambiamos nada de la aplicación y todos los campos siguen siendo enviados como hace 3-4 meses. Hubo algún breaking change?

**Comment by drarko** [comment]
Estimado,
¿En que servicio se da ese error?
