### ISSUE TITLE
Error 702 "Cuenta de vendedor inválida"

### ISSUE THREAD

**Issue by sebaherrera** [TodoPago/SDK-PHP#70]
# SDK-PHP | Issue Técnico
> Poner un problema en su respectivo contexto acelera su resolución. </br>

Usé el código de ejemplo que está en el readme para probar en ambiente "test" con las credenciales de "Pruebas" que salen en la página. Haga lo que haga, obtengo: el error 702 "Cuenta de vendedor inválida".

> __Para consultas acerca de nuevas funcionalidades o información comercial utiliza el formulario de contacto de www.todopago.com.ar__

## Requisitos

* [X] ¿Habilitaste la extensión SOAP de PHP?
* [X] ¿Habilitaste la extensión CURL de PHP?
* [X] ¿Habilitaste la extensión openSSL de PHP?
* [X] ¿Seguiste los pasos de instalación descritos en [README.md](https://github.com/TodoPago/dev-sdk-php/blob/master/README.md)?
* [x] Completar con una X dentro de los corchetes para los requisitos cumplidos.

## Comportamiento esperado
> Describinos qué respuesta se espera.

Recibir la URL del formulario de pago

## Comportamiento actual
> Describinos qué está sucediendo actualmente.

Error 702 "Cuenta de vendedor inválida"

## Pasos a reproducir
> Contanos, con el mayor detalle posible, qué pasos realizar para replicar el error.

Código relevante:

$mode = "test";//identificador de entorno obligatorio, la otra opción es "prod"
$http_header = array('Authorization'=>'TODOPAGO f103545ba9554bfc8ea5fcb2b87b840f');//authorization key del ambiente requerido
$connector = new TodoPago\Sdk($http_header, $mode);

$optionsSAR_comercio = array (
	'Security'=> 'f103545ba9554bfc8ea5fcb2b87b840f',
	'EncodingMethod'=>'XML',
	'Merchant'=> 1306000,
	'URL_OK'=>'localhost:8888/sdk-php/ejemplo/exito.php?Order=27398173292187',
	'URL_ERROR'=>'localhost:8888/sdk-php/ejemplo/error.php?Order=27398173292187'
);

$optionsSAR_operacion = array (
	'MERCHANT'=> 1306000,
....

## Entorno
> Completar con las versiones de las distintas herramientas aplicadas.
+ Entorno
  * __SO: Debian 3.16.59-1
  * __Servidor Web y versión: Apache 2.4.10
  * __Versión de PHP: 7.2.9 De ser posible, link a phpinfo()_
  * __Versión de SDK: la última que baja Composer, que sería la 1.10.1
  * __Ambiente de Todopago: test

## Comentario
> Cualquier cosa que quieras comentas que consideres pueda aportar a la detección y resolución del problema.

Es muy engorroso, ante cada error, tener que estar googleando para ver si alguien tiene una mínima pista en algún lado. Deberían documentarlos mejor. Muchas gracias.

**Comment by sebaherrera** [comment]
Nunca va a funcionar en test porque el endpoint apunta a https://developers.todopago.com.ar/

¿Están actualizando este SDK o quedó abandonado?

**Comment by marcosdipaolo** [comment]
Parece que está totalmente abandonado. Me pregunto si no implementar mercadopago ya mismo.

**Comment by sebaherrera** [comment]
Ya me pasé a Mercadopago. Estuve una semana entera validando los datos del vendedor en el 0800 para que, una semana después, me llegara un mail preguntando qué pasaba. Así no se puede trabajar.

**Comment by Medr3x** [comment]
Buenas, fijense en este issue: #14 

Si miran el codigo de ejemplo, esta funcion:

function getHeader($apikey){
	return array('Authorization'=>$apikey,
		'user_agent' => 'PHPSoapClient');
}

Al agregarle esto a la variable api_keys deja de tirar el error 702. Y arma la preferencia pago!

Saludos

**Comment by sebaherrera** [comment]
¡Gracias! Igual ya lo tuvimos que abandonar -y recomendar a otros clientes que no lo usen- porque el soporte es prácticamente nulo.

**Comment by curcio79** [comment]
Nos disculpamos por la demora en la respuesta y lamentamos mucho que hayas tenido este inconveniente. Si necesitás ayuda, llamanos al  0800-333-0010 o escribinos a contacto@todopago.com.ar
