### ISSUE TITLE
No puedo generar Api Key de Prueba

### ISSUE THREAD

**Issue by braianjchristiansen** [TodoPago/SDK-PHP#71]
Buenos dias,

Mi problema es tan simple que ni deberia ingresarlo por aqui, pero ya estoy medio desesperado porque desde la pagina de todo pago nadie me contesta.
Necesito generarme un usuario de tipo Developer en la pagina de todo pago, y no puedo realizarlo.
Tengo mi usuario comun, el cual no puedo utilizar como developer. No se si es un problema del sitio, o realmente son 2 usuarios distintos que hay que tener (uno para una cuenta comun, y otro que sirva como developer).

Ingresando con mi usuario comun, puedo ver mi api key de produccion, pero no me deja generar la api key de prueba.

Hay alguna forma que alguien me pueda ayudar? Necesito un usuario developer, para poder integrarme. Hay algun contacto que pueda utilizar para hablar con alguien directamente sobre este tema?

Muchas gracias

**Comment by santiagodonnell** [comment]
Tengo exactamente el mismo problema. Entiendo que para obtener las Api Key de prueba debes convertirte en usuario vendedor. Cargar datos de una cuenta de banco, inscripción a Afip, etc.

Ahora, lo que no se o no esta claro, es como registrarse al portal de developers. Cuando lo quise hacer desde aquí https://portal.developers.todopago.com.ar/app/#login me  registro como un usuario común.

**Comment by azche** [comment]
Me pasa exactamente lo mismo.
@braianjchristiansen @santiagodonnell Encontraron alguna solución? Gracias, saludos.

**Comment by braianjchristiansen** [comment]
@azche nunca funcionó lamentablemente... Incluso intenté conversar con alguien de adentro, y no tuve mucha respuesta del tema... sencillamente no está funcionando la generación de usuarios de prueba.
Te paso unos datos que me proporcionaron en su momento que puede ayudar para avanzar (al menos a mi me ayudo)...
Merchant: 949386
Security: D2D4AAACA41E48979820B57536ABB35F

Son datos de prueba... no tengo el usuario de prueba de esos datos, pero si la información esa que puede ayudar.
Espero que sirva.
Saludos.

**Comment by azche** [comment]
> @azche nunca funcionó lamentablemente... Incluso intenté conversar con alguien de adentro, y no tuve mucha respuesta del tema... sencillamente no está funcionando la generación de usuarios de prueba.
> Te paso unos datos que me proporcionaron en su momento que puede ayudar para avanzar (al menos a mi me ayudo)...
> Merchant: 949386
> Security: D2D4AAACA41E48979820B57536ABB35F
> 
> Son datos de prueba... no tengo el usuario de prueba de esos datos, pero si la información esa que puede ayudar.
> Espero que sirva.
> Saludos.

Gracias @braianjchristiansen!

**Comment by curcio79** [comment]
@ngrunfeld @braianjchristiansen fijense q la info esta en el portal de TP, tengan en cuenta q quizas les pida q esten habilitados como vendedores

![image](https://user-images.githubusercontent.com/79460573/115237942-842d7200-a0f3-11eb-9cc4-e9c9dffede1c.png)
