### ISSUE TITLE
Formulario Híbrido - Acredita pago, pero devuelve error

### ISSUE THREAD

**Issue by braianjchristiansen** [TodoPago/SDK-PHP#73]
# SDK-PHP | Issue Técnico
>El problema que tengo es implementando el formulario híbrido... al utilizarlo para pagar con billetera virtual me arroja un error, aunque el pago se acredita correctamenete </br>
Esta guía tiene como objetivo contextualizar el inconveniente desde un primer momento.

> __Para consultas acerca de nuevas funcionalidades o información comercial utiliza el formulario de contacto de www.todopago.com.ar__

## Requisitos

* [x] ¿Habilitaste la extensión SOAP de PHP?
* [x] ¿Habilitaste la extensión CURL de PHP?
* [x] ¿Habilitaste la extensión openSSL de PHP?
* [x] ¿Seguiste los pasos de instalación descritos en [README.md](https://github.com/TodoPago/dev-sdk-php/blob/master/README.md)?
* [x] Completar con una X dentro de los corchetes para los requisitos cumplidos.

## Comportamiento esperado
> La función billeteraPaymentResponse debería devolver un mensaje de pago OK. Sin embargo, si realizo el pago con tarjetas, funciona correctamente.

## Comportamiento actual
> Cuando se confecciona el pago con la billetera virtual, acredita el pago pero devuelve el siguiente error el callback:

My wallet callback
{ResultCode: "-999", ResultMessage: "Ha ocurrido un error inesperado.", RedirectURL: "", BILLETERA: true}

## Pasos a reproducir
> Se toma como ejemplo del formulario híbrido que dispone todo pago en el SDK. Se ingresa en ese formulario un public-request_key para poder pagar. Una vez cargada la pagina se opta por pagar con billetera virtual. Se inicia sesión en todo pago, y se seleccionar la billetera virtual. Se paga con ella y arroja el error mencionado arriba. Sin embargo, el pago igualmente se acredita.

## Entorno
> Completar con las versiones de las distintas herramientas aplicadas.
+ Entorno
  * __SO:_WINDOWS_
  * __Servidor Web y versión:_APACHE XAMPP_7.4.5
  * __Versión de PHP:_7.4.5_ _De ser posible, link a phpinfo()_
  * __Versión de SDK:_la actual_
  * __Ambiente de Todopago:_Producción_

## Comentario
> Cualquier cosa que quieras comentas que consideres pueda aportar a la detección y resolución del problema.
LOG COMPLETO:
10A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at <URL> and <URL>.
TPHybridForm-v0.1.js:1794 Cargando API Todo Pago para formulario Híbrido / BSAv1.1.36
TPHybridForm-v0.1.js:1794 Seteando Item
todopagohibrido.php:223 Cargando
todopagohibrido.php:226 Stop loading...
todopagohibrido.php:223 Cargando
todopagohibrido.php:226 Stop loading...
jquery.min.js:4 POST https://forms.todopago.com.ar/t/1.2/api/WalletPaymentSaldoVirtualApi 500 (Internal Server Error)
send @ VM20 jquery.min.js:4
ajax @ VM20 jquery.min.js:4
realizarPagoStep2CV @ VM23 billetera.js:744
realizarPago @ VM23 billetera.js:659
(anonymous) @ VM23 billetera.js:488
dispatch @ VM20 jquery.min.js:3
r.handle @ VM20 jquery.min.js:3
jquery.min.js:4 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ VM20 jquery.min.js:4
ajax @ VM20 jquery.min.js:4
sessionDestroy @ VM23 billetera.js:777
error @ VM23 billetera.js:769
j @ VM20 jquery.min.js:2
fireWith @ VM20 jquery.min.js:2
x @ VM20 jquery.min.js:4
b @ VM20 jquery.min.js:4
XMLHttpRequest.send (async)
send @ VM20 jquery.min.js:4
ajax @ VM20 jquery.min.js:4
realizarPagoStep2CV @ VM23 billetera.js:744
realizarPago @ VM23 billetera.js:659
(anonymous) @ VM23 billetera.js:488
dispatch @ VM20 jquery.min.js:3
r.handle @ VM20 jquery.min.js:3
billetera.js:783 Session destroyed
todopagohibrido.php:208 My wallet callback
todopagohibrido.php:209 -999 : Ha ocurrido un error inesperado.
todopagohibrido.php:210 {ResultCode: "-999", ResultMessage: "Ha ocurrido un error inesperado.", RedirectURL: "", BILLETERA: true}BILLETERA: trueRedirectURL: ""ResultCode: "-999"ResultMessage: "Ha ocurrido un error inesperado."__proto__: Object

**Comment by braianjchristiansen** [comment]
Alguien mirando este foro??? Necesito ayuda urgente con este tema. Gracias

**Comment by braianjchristiansen** [comment]
Alguien me podría ayudar con este problema? Necesito usar el formulario híbrido.

**Comment by curcio79** [comment]
@braianjchristiansen buenos dias, por lo q veo estas trabajando en una maquina local no? estas usando un iframe?

**Comment by curcio79** [comment]
@braianjchristiansen veo q tenes varios tickets abiertos, terminamos con este ticket y seguimos con el resto?

**Comment by braianjchristiansen** [comment]
hola @curcio79 entendería que si... cuando le das al botón <button id="MY_btnPagarConBilletera" class="tp-button btn btn-info btn-billetera-pago-comision"/> abre un popup (entendería el iframe) con el login de todo pago. Y desde allí intento pagar con la billetera... el callback tira el error descripto.
Si... en principio estoy desde el localhost.

**Comment by curcio79** [comment]
@braianjchristiansen hace una cosa al hacer click q sea a un target="_blank" solo a la url donde esta el codigo del hibrido y decime si te genera el error

**Comment by braianjchristiansen** [comment]
@curcio79  dale... dejame que lo pruebo durante el día, y mas tardar hoy a la tarde o mañana temprano te comento los resultados.
Muchas gracias por tu ayuda.

**Comment by curcio79** [comment]
Dale, espero tu respuesta @braianjchristiansen asi si esta todo bien cerramos los ticket

**Comment by braianjchristiansen** [comment]
@curcio79  disculpame... a que te referís con código del híbrido? intenté meterle un target blank al button pero sin exito... continúa abriendo el iframe.
donde debería meter el _blank?

Gracias.

**Comment by curcio79** [comment]
@braianjchristiansen lo q me indica el error es un iframe q no es generado por el sdk, por eso quiero asegurarme de q llegues al archivo php limpio y veamos si es eso, o otra cosa

**Comment by braianjchristiansen** [comment]
@curcio79 el problema es que no tengo manera de decirle que habrá la pagina en blank.. lo maneja solo el js que consumo de TP. Simplemente uso el código de ejemplo que tiene el SDK + un estilo "lindo" para mi ecommerce.
El resto lo hace solo el sdk

**Comment by curcio79** [comment]
@braianjchristiansen me pasas el reporte de logs de js?

**Comment by braianjchristiansen** [comment]
Buenas tardes @curcio79, disculpame la demora. No tuve tiempo de replicar el error para enviartelo... acá te dejo el log:

TPBSAForm.min.js:1 Cargando API Todo Pago para formulario Híbrido / BSAv2.0
TPBSAForm.min.js:1 Seteando Item
pagoComision.php?publicRequesKey=u5b4ab045-c169-4cbe-9005-ac72a56dbd0d&periodoActual=2042021:705 Cargando
pagoComision.php?publicRequesKey=u5b4ab045-c169-4cbe-9005-ac72a56dbd0d&periodoActual=2042021:1 [DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input id=​"tokenPeiTxt" maxlength=​"6" type=​"password" placeholder=​"Ingresá el código de 6 dígitos" style=​"display:​ none;​">​
pagoComision.php?publicRequesKey=u5b4ab045-c169-4cbe-9005-ac72a56dbd0d&periodoActual=2042021:708 Stop loading...
check.js?org_id=k8vif92e&session_id=decidir_todopago66e1269d-cb00-9d97-5612-8058d6d693de&_=1619719366346:440 [Deprecation] RTP data channels are no longer supported. The "RtpDataChannels" constraint is currently ignored, and may cause an error at a later date.
setup @ check.js?org_id=k8vif92e&session_id=decidir_todopago66e1269d-cb00-9d97-5612-8058d6d693de&_=1619719366346:440
addFeature @ check.js?org_id=k8vif92e&session_id=decidir_todopago66e1269d-cb00-9d97-5612-8058d6d693de&_=1619719366346:479
td_h2 @ check.js?org_id=k8vif92e&session_id=decidir_todopago66e1269d-cb00-9d97-5612-8058d6d693de&_=1619719366346:418
td_5k @ check.js?org_id=k8vif92e&session_id=decidir_todopago66e1269d-cb00-9d97-5612-8058d6d693de&_=1619719366346:380
td_e @ check.js?org_id=k8vif92e&session_id=decidir_todopago66e1269d-cb00-9d97-5612-8058d6d693de&_=1619719366346:376
setTimeout (async)
(anonymous) @ check.js?org_id=k8vif92e&session_id=decidir_todopago66e1269d-cb00-9d97-5612-8058d6d693de&_=1619719366346:374
load (async)
td_2w @ check.js?org_id=k8vif92e&session_id=decidir_todopago66e1269d-cb00-9d97-5612-8058d6d693de&_=1619719366346:374
td_3m @ check.js?org_id=k8vif92e&session_id=decidir_todopago66e1269d-cb00-9d97-5612-8058d6d693de&_=1619719366346:378
(anonymous) @ check.js?org_id=k8vif92e&session_id=decidir_todopago66e1269d-cb00-9d97-5612-8058d6d693de&_=1619719366346:874
check.js?org_id=k8vif92e&session_id=decidir_todopago66e1269d-cb00-9d97-5612-8058d6d693de&_=1619719366346:376 [Violation] 'setTimeout' handler took 257ms
check.js?org_id=k8vif92e&session_id=decidir_todopago66e1269d-cb00-9d97-5612-8058d6d693de&_=1619719366346:648 GET chrome-extension://invalid/ net::ERR_BLOCKED_BY_CLIENT
td_d5 @ check.js?org_id=k8vif92e&session_id=decidir_todopago66e1269d-cb00-9d97-5612-8058d6d693de&_=1619719366346:648
setup @ check.js?org_id=k8vif92e&session_id=decidir_todopago66e1269d-cb00-9d97-5612-8058d6d693de&_=1619719366346:655
addFeature @ check.js?org_id=k8vif92e&session_id=decidir_todopago66e1269d-cb00-9d97-5612-8058d6d693de&_=1619719366346:479
td_h2 @ check.js?org_id=k8vif92e&session_id=decidir_todopago66e1269d-cb00-9d97-5612-8058d6d693de&_=1619719366346:419
td_5k @ check.js?org_id=k8vif92e&session_id=decidir_todopago66e1269d-cb00-9d97-5612-8058d6d693de&_=1619719366346:380
td_e @ check.js?org_id=k8vif92e&session_id=decidir_todopago66e1269d-cb00-9d97-5612-8058d6d693de&_=1619719366346:376
setTimeout (async)
(anonymous) @ check.js?org_id=k8vif92e&session_id=decidir_todopago66e1269d-cb00-9d97-5612-8058d6d693de&_=1619719366346:374
load (async)
td_2w @ check.js?org_id=k8vif92e&session_id=decidir_todopago66e1269d-cb00-9d97-5612-8058d6d693de&_=1619719366346:374
td_3m @ check.js?org_id=k8vif92e&session_id=decidir_todopago66e1269d-cb00-9d97-5612-8058d6d693de&_=1619719366346:378
(anonymous) @ check.js?org_id=k8vif92e&session_id=decidir_todopago66e1269d-cb00-9d97-5612-8058d6d693de&_=1619719366346:874
check.js?org_id=k8vif92e&session_id=decidir_todopago66e1269d-cb00-9d97-5612-8058d6d693de&_=1619719366346:800 [Violation] 'complete' handler took 218ms
pagoComision.php?publicRequesKey=u5b4ab045-c169-4cbe-9005-ac72a56dbd0d&periodoActual=2042021:705 Cargando
ruxitagentjs_ICA2SVf…5180105125946.js:15 Initconfig not found or agent already initialized! This is an injection issue.
ruxitagentjs_ICA2SVf…5180105125946.js:86 Duplicate agent injection detected or no initCode available, turning off redundant core.
[Violation] Forced reflow while executing JavaScript took 65ms
commands:1 [DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input type=​"password" class=​"form-control form-control-reducido passwd" autocomplete=​"off" name=​"billetera-pass" id=​"billetera-passTxt" placeholder=​"Contraseña" readonly onfocus=​"this.removeAttribute('readonly')​;​">​
commands:1 [DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input id=​"tokenPeiTxt" onchange=​"validarTokenPei()​" type=​"password" class=​"form-control cleanChangeMP" placeholder=​"Ingresa tu código de 6 dígitos" maxlength=​"6" minlength=​"6" data-num autocomplete=​"off">​
commands:1 [DOM] Input elements should have autocomplete attributes (suggested: "current-password"): (More info: https://goo.gl/9p2vKq) <input type=​"password" style=​"display:​none">​
pagoComision.php?publicRequesKey=u5b4ab045-c169-4cbe-9005-ac72a56dbd0d&periodoActual=2042021:708 Stop loading...
check.js:652 [Deprecation] RTP data channels are no longer supported. The "RtpDataChannels" constraint is currently ignored, and may cause an error at a later date.
setup @ VM381 check.js:652
addFeature @ VM381 check.js:60
td_pm @ VM381 check.js:694
td_1p @ VM381 check.js:656
td_e @ VM381 check.js:498
setTimeout (async)
(anonymous) @ VM381 check.js:496
load (async)
td_2b @ VM381 check.js:496
td_0k @ VM381 check.js:500
(anonymous) @ VM381 check.js:874
VM381 check.js:498 [Violation] 'setTimeout' handler took 1110ms
check.js:726 GET chrome-extension://invalid/ net::ERR_BLOCKED_BY_CLIENT
td_z8 @ VM381 check.js:726
setup @ VM381 check.js:733
addFeature @ VM381 check.js:60
td_pm @ VM381 check.js:695
td_1p @ VM381 check.js:656
td_e @ VM381 check.js:498
setTimeout (async)
(anonymous) @ VM381 check.js:496
load (async)
td_2b @ VM381 check.js:496
td_0k @ VM381 check.js:500
(anonymous) @ VM381 check.js:874
VM381 check.js:104 [Violation] 'complete' handler took 289ms
VM355 jquery.min.js:4 [Violation] 'readystatechange' handler took 151ms
jquery.min.js:4 POST https://forms.todopago.com.ar/t/1.2/api/WalletPaymentSaldoVirtualApi 422 (Unprocessable Entity)
send @ VM355 jquery.min.js:4
ajax @ VM355 jquery.min.js:4
realizarPagoStep2CV @ VM361 billetera.js:744
realizarPago @ VM361 billetera.js:659
(anonymous) @ VM361 billetera.js:488
dispatch @ VM355 jquery.min.js:3
r.handle @ VM355 jquery.min.js:3
jquery.min.js:4 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ VM355 jquery.min.js:4
ajax @ VM355 jquery.min.js:4
sessionDestroy @ VM361 billetera.js:777
error @ VM361 billetera.js:769
j @ VM355 jquery.min.js:2
fireWith @ VM355 jquery.min.js:2
x @ VM355 jquery.min.js:4
b @ VM355 jquery.min.js:4
XMLHttpRequest.send (async)
send @ VM355 jquery.min.js:4
ajax @ VM355 jquery.min.js:4
realizarPagoStep2CV @ VM361 billetera.js:744
realizarPago @ VM361 billetera.js:659
(anonymous) @ VM361 billetera.js:488
dispatch @ VM355 jquery.min.js:3
r.handle @ VM355 jquery.min.js:3
billetera.js:783 Session destroyed
VM355 jquery.min.js:4 [Violation] 'readystatechange' handler took 156ms
pagoComision.php?publicRequesKey=u5b4ab045-c169-4cbe-9005-ac72a56dbd0d&periodoActual=2042021:663 My wallet callback
pagoComision.php?publicRequesKey=u5b4ab045-c169-4cbe-9005-ac72a56dbd0d&periodoActual=2042021:664 Response 1: -999 : Ha ocurrido un error inesperado.
pagoComision.php?publicRequesKey=u5b4ab045-c169-4cbe-9005-ac72a56dbd0d&periodoActual=2042021:665 Response 2: [object Object]

Como verás, al final del log, muestra los mensajes genéricos de error:

Te comento rapidamente los pasos realizados:
1- Envío de SAR, y recepción correcta.
2- Apertura de Formulario híbrido con public key
3- Oprimo botómn de pagar con billetera.
4- Abre el login de Todo pago
5- Logueo con mi cuenta de usuario para hacer el pago
6- Selección de saldo virtual para pagar
7- devuelve call back con error mencionado.

Quedo atento a la información que necesites para poder ayudarme a resolver este issue.

Gracias.

**Comment by curcio79** [comment]
@braianjchristiansen hay un incidente con saldo virtual para este tipo de formularios y que se está revisando, te recomiendo deshabilitarlo y te notifico dentro del SDK cuando este corregido.

**Comment by braianjchristiansen** [comment]
tendrás algun estimado? Porque hace mas de 1 año que lo intento usar, y siempre falla.
