### ISSUE TITLE
¿SDK Deprecado?

### ISSUE THREAD

**Issue by lucasbraintly** [TodoPago/SDK-PHP#74]
Hola! Este SDK se encuentra deprecado? veo que el endpoint https://developers.todopago.com.ar/ ya no funciona y hay muchos issues en Github sin responder.

¿Cuál es el estado de esto? no estoy pudiendo integrar y no encuentro información en ningún lado.

**Comment by alerolon15** [comment]
Buenas tardes.
Probá cambiando el endpoint https://developers.todopago.com.ar/ por https://apis.developers.todopago.com.ar/
y contanos si te funciona.
Saludos

**Comment by braianjchristiansen** [comment]
Buenas tardes,
Yo tengo implementado Todo Pago en e-commerce. Hace varios días que no funciona el entorno de Test.
Intenté realizar el cambio del endpoint como mencina @alerolon15 pero obtuve el mismo resultado.
Lo llamativo es que el error se presenta cuando el responseSAR devuelve vacío.

array(2) { ["StatusCode"]=> NULL ["StatusMessage"]=> string(0) "" }
Send Authorize Request Error

No se que sucede.

**Comment by alerolon15** [comment]
@braianjchristiansen podes volver a probar nuevamente el caso ? deberia dejar de devolver null

**Comment by braianjchristiansen** [comment]
@alerolon15 mil gracias! comenzó a funcionar de manera perfecta ahora!
EndPoint de siempre: https://developers.todopago.com.ar/
Un abrazo!

**Comment by azche** [comment]
Buenas.. test dejó de funcionar otra vez? Me devuelve NULL con los dos endpoints

**Comment by braianjchristiansen** [comment]
@azche como estás?
Mira... desde la integración avanzada, acabo de hacer una prueba en TEST con las tarjetas de prueba que actualizaron en la pag de TP y funcionó OK.
Que integración estás usando? Formulario híbrido? o estás usando el proceso del ejemplo completo que dispone TP?

**Comment by azche** [comment]
Claro, siguiendo el ejemplo_simple:

$connector = new Sdk($http_header, $mode);
...
$rta = $connector->sendAuthorizeRequest($optionsSAR_comercio, $optionsSAR_operacion);

me devuelve NULL con $mode test

y con $mode = 'prod' :

Array
(
    [StatusCode] => -1
    [StatusMessage] => Solicitud de Autorizacion Registrada
    [URL_Request] => https://forms.todopago.com.ar/formulario/commands?command=formulario&m=xxxxx&fr=1
    [RequestKey] => xxxxxxx
    [PublicRequestKey] => xxxxx
)

**Comment by braianjchristiansen** [comment]
@azche mmmm extraño...
Mirá en mi experiencia chocándome contra la pared con este SDK, las veces en las que me devolvió NULL es porque algún dato que le estás enviando en el array $operationsSAR_operacion no le gusta.... me sucedió con los montos particularmente... y lo mas extraño es que  a veces te devuelve el error de formato (con los códigos que muestra el manual) o a veces NULL como en este caso... 
Revisate bien la info que estás mandando y cruza los tipos de datos, longitudes, formatos, etc con lo que muestra el manual por cada campo.

Por otro lado, asegurate de estar usando los EndPoints correctos...

TODOPADO_ENDPOINT_TEST --> 'https:///developers.todopago.com.ar/'
TODOPAGO_ENDPOINT_TEST_FORM --> 'https://developers.todopago.com.ar/resources/TPHybridForm-v0.1.js' (híbrido)

El SDK está funcionando para TEST... te lo confirmo porque acabo de hacer una nueva prueba para estar seguro.

Saludos.

**Comment by azche** [comment]
Gracias @braianjchristiansen , aparentemente eran las keys. las que me pasaste en el otro issue lo solucionaron.
Evidentemente no son iguales los endpoints en los dos entornos. Si pongo keys incorrectas en prod me devuelve un mensaje acorde pero en test me devuelve null.

Gracias de nuevo, saludos!

**Comment by braianjchristiansen** [comment]
Excelente @azche !!!!! Abrazo
