### ISSUE TITLE
Formulario web de pago - Error con cualquier tarjeta

### ISSUE THREAD

**Issue by braianjchristiansen** [TodoPago/SDK-PHP#75]
# SDK-PHP | Issue Técnico
El problema que tengo es que el formulario de pago web productivo, comenzó a arrojar el mismo error desde hace unos días. Con cualquier tarjeta que se intente, falla devolviendo el mismo error siempre.

## Requisitos

* [ X] ¿Habilitaste la extensión SOAP de PHP?
* [ X] ¿Habilitaste la extensión CURL de PHP?
* [ X] ¿Habilitaste la extensión openSSL de PHP?
* [ X] ¿Seguiste los pasos de instalación descritos en [README.md](https://github.com/TodoPago/dev-sdk-php/blob/master/README.md)?
* [x] Completar con una X dentro de los corchetes para los requisitos cumplidos.

## Comportamiento esperado
Las tarjetas se deben validar correctamente, y se debe efectivizar el pago.

## Comportamiento actual
Falla cualquier tarjeta con la que se intente pagar.
El responseSAR es correcto.
ResponseSAR:
{"StatusCode":-1,"StatusMessage":"Solicitud de Autorizacion Registrada","URL_Request":"https://forms.todopago.com.ar/formulario/commands?command=formulario&m=u50d85ce9-3c89-4500-b487-b35f0fed39fb&fr=1","RequestKey":"67441d1e-f8d6-403c-982b-32046a3d48a7","PublicRequestKey":"u50d85ce9-3c89-4500-b487-b35f0fed39fb"}

Pero el responseGAA siempre arroja el siguiente error:
{"StatusCode":99999,"StatusMessage":"Tu compra no pudo realizarse. Iniciala nuevamente utilizando otro medio de pago.".....

## Pasos a reproducir
1- Confirmar compra. El sitio web redirige al forumario de pago de todo pago.
2- Se ingresan los datos de tarjeta en el formulario de TP
3- Devuelve al sitio web con el error descripto arriba, para cualquier caso.

## Entorno
> Completar con las versiones de las distintas herramientas aplicadas.
+ Entorno
  * __SO:__WINDOWS
  * __Servidor Web y versión:__APACHEXAMPP 7.4.5
  * __Versión de PHP:__ _7.4.5
  * __Versión de SDK:__actual
  * __Ambiente de Todopago:__Producción

## Comentario
> Cualquier cosa que quieras comentas que consideres pueda aportar a la detección y resolución del problema.

**Comment by alerolon15** [comment]
Buenas tardes @braianjchristiansen 
Te dejo dos tarjetas que deberian aprobarte de forma correcta:
"4517510000020087" - ICBC Debito Visa
"4546400034748181" - Galicia credito Visa

Para el pago en el formulario, podes ingresar fecha de vencimiento 01/30 y CVV "123"

Gracias por avisar, así podemos actualizar los datos de prueba del sitio.
Saludos

**Comment by braianjchristiansen** [comment]
Gracias por la información @alerolon15, pero ojo que en este caso estoy hablando del ambiente productivo.
Lo llamativo es que no funciona con ninguna tarjeta, y de hecho me he comunicado con mis emisores, y me comentaron que en términos de banco y emisor de tarjeta no hay ningún impedimento para concretar el pago.
Hace poco mas de 1 semana me comuniqué con TP para levantar el problema, y me brindaron el número de reclamo CAS1242557
Me respondieron ayer indicando que vuelva a intentar el pago.... pero mismo resultado. Error, y con el mismo mensaje.

Gracias,
Saludos.

**Comment by alerolon15** [comment]
@braianjchristiansen cual es el ID de cuenta del usuario vendedor ?

**Comment by braianjchristiansen** [comment]
@alerolon15 , MerchantId: 3512035- UsuarioTP: multiequip7@gmail.com

**Comment by braianjchristiansen** [comment]
@alerolon15 comentame si necesitas alguna información adicional por favor.. mil gracias por tu ayuda

**Comment by alerolon15** [comment]
@braianjchristiansen veo que los rechazos vienen desde el sistema de seguridad de tarjetas,
unas por tarjeta invalida y otras por algún problema en los datos de la tarjeta.
es un sistema ajeno a TodoPago, pero generalmente ocurren porque no se están enviando bien los datos de la tarjeta de crédito o debito.
ya sea CVV, Fecha expiración o Nombre que figura en la tarjeta (recordá enviar los datos del nombre en mayúsculas y tal cual figura en el plástico)

Probá corroborando bien los datos y enviandolos correctamente o directamente con otra tarjeta
y avisame

**Comment by braianjchristiansen** [comment]
@alerolon15 cómo estás?
Mira probé con 4 tarjetas distintas(débito y crédito)... ninguna me la aceptó. Probé con ingresar la información de distintos modos, pero no tuve éxito.
Como se podrá hacer para solucionar esto? Se podrá abrir algún reclamo en algún lado?

**Comment by braianjchristiansen** [comment]
@alerolon15  como estás?

Nuevamente están fallando las tarjetas de pruebas...

"4517510000020087" - ICBC Debito Visa
"4546400034748181" - Galicia credito Visa

Podrías ayudarme con esto? Habrá otros numeros de prueba para utilizar?

Gracias

**Comment by curcio79** [comment]
@braianjchristiansen aca te paso un listado


Nro de Tarjeta | Tipo de Tarjeta | CCV | Vencimiento
-- | -- | -- | --
4546400034748181 | Visa Crédito | 123 | 10/30
4517510000020087 | Visa Crédito | 123 | 10/30



Nro de Tarjeta | Tipo de Tarjeta | Resultado
-- | -- | --
4242424242424242 | VISA | 99955 - La tarjeta ingresada es invalida.
4012888888881881 | VISA | 99955 - La tarjeta ingresada es invalida.
5555555555554444 | MasterCard | 99997 - En este momento la operación no pudo ser realizada. Por favor intentá más tarde.
378282246310005 | AmEx | 99955 - La tarjeta ingresada es invalida.
371449635398431 | AmEx | 99955 - La tarjeta ingresada es invalida.
30569309025904 | Diners Club | 99997 - En este momento la operación no pudo ser realizada. Por favor intentá más tarde.
38520000023237 | Diners Club | 99997 - En este momento la operación no pudo ser realizada. Por favor intentá más tarde.
4000000000000010 | VISA | 99955 - La tarjeta ingresada es invalida.

**Comment by curcio79** [comment]
@braianjchristiansen sobre la segunda tabla, solo se aprobarán las transacciones entre los montos de $ 1,00 y $ 999,00. Además, podés realizar pruebas de transacciones rechazadas y analizar los mensajes de error:

**Comment by braianjchristiansen** [comment]
muchas gracisa!

**Comment by andreszs** [comment]
Tengo exacto el mismo problema, solo funcionó bien en producción el primer pago que hice con una tarjeta de débito, de ahi en mas TODOS los pagos son rechazados con el mismo error genérico de _intentar con otro medio_. Probe tarjetas de mucha gente, siempre poniendo nombres en mayusculas tal como figuran en la tarjeta. Todas son rechazadas. Una lástima porque estaba interesado en implementar TP como alternativo a MercadoPago en una red social para cuentas premium.

**Comment by seraguirre** [comment]
> Tengo exacto el mismo problema, solo funcionó bien en producción el primer pago que hice con una tarjeta de débito, de ahi en mas TODOS los pagos son rechazados con el mismo error genérico de _intentar con otro medio_. Probe tarjetas de mucha gente, siempre poniendo nombres en mayusculas tal como figuran en la tarjeta. Todas son rechazadas. Una lástima porque estaba interesado en implementar TP como alternativo a MercadoPago en una red social para cuentas premium.
> 
> PD. el soporte telefonico de TodoPago me dijo que "**_cada cliente debe comunicarse con su banco emisor (?) para que autorice la tarjeta_**", o sea un absurdo totalmente inviable. No se puede pedir a cada cliente que se comunique con su emisor de tarjeta para autorizarle un pago de 75 pesos.

Por qué cerraron este post? A mí me pasa exactamente lo mismo y todavía no encuentro solución. @andreszs Vos cómo lo solucionaste?

**Comment by andreszs** [comment]
@seraguirre Lo solucione haciendo que los usuarios ingresen todos los datos de control de fraude que piden los bancos, o sea esos campos que empiezan con **CSBT** tienen que estar lo mas completo y exacto posibles. Podes ver la implementacion en argim.net, activar Gold > todopago > datos facturacion. Saludos

**Comment by seraguirre** [comment]
> @seraguirre Lo solucione haciendo que los usuarios ingresen todos los datos de control de fraude que piden los bancos, o sea esos campos que empiezan con **CSBT** tienen que estar lo mas completo y exacto posibles. Podes ver la implementacion en argim.net, activar Gold > todopago > datos facturacion. Saludos

Y una pregunta más... cómo hacés con los usuario que tienen IPv6? Porque la api de TodoPago soporta formato IPv4 solamente.

**Comment by andreszs** [comment]
La documentacion estara desactualizada, estoy enviando el REMOTE_ADDR sin preguntar por la version del protocolo IP sin ningun problema.

**Comment by seraguirre** [comment]
> La documentacion estara desactualizada, estoy enviando el REMOTE_ADDR sin preguntar por la version del protocolo IP sin ningun problema.

Ah! ojo con eso. Quizás no te tocó ninguna IPv6 o no te enteraste. No es algo que está en la documentación, sinó que es algo que sucede en producción. Yo lo vi de casualidad porque justo probé desde una conexión con IPv6 y me devuelve siempre el siguiente error: "El formato del campo CSBTIPADDRESS es incorrecto (IPv4)" como dando a entender que sólo soportan ese formato.
Espero te sirva este dato!

Saludos!

**Comment by curcio79** [comment]
@seraguirre te respondi en el otro issue, el problema ya esta reportado para su solucion. Mientras tanto puedo pasarte una funcion de conversion y asi no te afecta sea IPV6 o IPV4

Saludos

**Comment by seraguirre** [comment]
> @seraguirre te respondi en el otro issue, el problema ya esta reportado para su solucion. Mientras tanto puedo pasarte una funcion de conversion y asi no te afecta sea IPV6 o IPV4
> 
> Saludos

@curcio79 Sí, perfecto. Si podés pasármela sería de gran ayuda. Gracias.

**Comment by curcio79** [comment]
La funcion ya se la pase, si alguien la necesita, no dude en solicitarla. Pero planificamos resolver el problema a la brevedad

Saludos a todos

**Comment by andreszs** [comment]
@curcio79 Espero que lo arreglen haciendo la conversion de su lado, aceptando IPV4+IPV6 en el mismo campo, asi nos ahorran ese trabajo al menos... gracias.

**Comment by curcio79** [comment]
TOTALMENTE de acuerdo. Pero mientras tanto quiero q tenga la solucion 🌞 

Saludos
