### ISSUE TITLE
DEPRECADO?

### ISSUE THREAD

**Issue by agus757** [TodoPago/SDK-PHP#78]
ACTUALICEN LA DOCUMENTACIÓN
EL FORMULARIO HÍBRIDO NO FUNCIONA COMO DEBERÍA
SI ESTA DEPRECADO PONGANLO, ASÍ NADIE PIERDE EL TIEMPO

**Comment by curcio79** [comment]
Hola buenos dias, q error te esta generando?

**Comment by agus757** [comment]
Hola buenas tardes, despues de pasar por un montón de errores, ahora lo que me esta haciendo es que en el formulario híbrido, no válida ni el mes ni el año, y entonces cuando pones los datos de tarjeta, aunque no pongas mes y año se envia igual el formulario

```
 <v-col cols="3" class="text-left">              
              <label class="caption-2 labelText">Mes</label>
              <select id="mesCbx"></select>
              <label id="fechaLbl"></label>
              <p class="error--text min-height mb-0" id="mesTxtError"></p>
            </v-col>
            <v-col cols="3" class="text-left">
              <label class="caption-2 labelText">Año</label>
              <select id="anioCbx"></select>
              <p class="error--text min-height mb-0" id="anioTxtError"></p>
            </v-col>
```

**Comment by curcio79** [comment]
@agus757 veo q hiciste un fork del plugin presta, es sobre el plugin o sobre esta sdk?

**Comment by agus757** [comment]
el fork lo hice para ver como estaba implementado el híbrido, porque en los sdk esta desactualizada la información, estoy usando el plugin de ruby, pero igualmente el problema esta en el híbrido que es indistinto al sdk

**Comment by curcio79** [comment]
acabo de verificar el hibrido de woo y no tuve el problema, cuales son los datos de tu ambiente de desarrollo?

**Comment by agus757** [comment]
ese es el otor problema, no anda con el js de desarrollo, estoy usaundo el de prod 
https://forms.todopago.com.ar/resources/TPBSAForm.min.js, reviso el plugin de woo, esta actualizado el repo?

**Comment by agus757** [comment]
Ya encontre el error, el js agrega el option mes y año con value -1 (<option value="-1">Mes</option><option value="-1">Año</option>)
Entonces no válida bien, porque esta tomando el mesCbx como el anioCbx como válido porque tiene un -1, con este fix se soluciona:

`const element = document.getElementById('numeroTarjetaTxt');
        element.addEventListener('change', (event) => {
          if (selectMes.options.length > 0 && selectMes.options[0].value == "-1") {
            document.getElementById('mesCbx').options[0].removeAttribute("value");
          }
          const selectAnio = document.getElementById('anioCbx');
          if (selectAnio.options.length > 0 && selectAnio.options[0].value == "-1") {
            document.getElementById('anioCbx').options[0].removeAttribute("value");
          }
        });`

**Comment by curcio79** [comment]
@agus757 entonces todo te quedo funcionando bien? Te puedo ayudar en algo?
