### ISSUE TITLE
sendAuthorizeRequest() devuelve null

### ISSUE THREAD

**Issue by DEV7163** [TodoPago/SDK-PHP#79]
## Requisitos

* [x] ¿Habilitaste la extensión SOAP de PHP?
* [x] ¿Habilitaste la extensión CURL de PHP?
* [x] ¿Habilitaste la extensión openSSL de PHP?
* [x] ¿Seguiste los pasos de instalación descritos en [README.md](https://github.com/TodoPago/dev-sdk-php/blob/master/README.md)?

## Comportamiento esperado
Obtener algún tipo de respuesta al ejecutar el método sendAuthorizeRequest() ya sea éxito o error

## Comportamiento actual
El método mencionado retorna null

## Entorno
> Completar con las versiones de las distintas herramientas aplicadas.
+ Entorno
  * Debian 10
  * Ngnix 1.18.0
  * PHP 7.4.15
  * Versión de SDK: 1.10.1
  * Ambiente de Todopago: Test
  

Veo en tickets anteriores que es un problema recurrente, me podrían dar una mano por favor, no veo como seguir debuggeando  a partir de acá, gracias.

**Comment by curcio79** [comment]
Lo tenes implementado online asi lo vemos?

**Comment by DEV7163** [comment]
Actualmente lo tengo implementado en un servidor de desarrollo que no es accesible desde internet.

**Comment by DEV7163** [comment]
Hace un rato hablé con mi cliente, dice que se comunicó telefónicamente con alguien de la plataforma quien le dijo que el problema es que no están dando acceso a la API a nuevos vendedores.

La verdad cuando me encargaron el trabajo de implementar pagos por esta via lo tomé para no dejar al cliente en banda, pero salta a la vista que es algo muy poco serio.
