### ISSUE TITLE
[Error] Ha habido un error. Por favor inténtelo de nuevo. Error 1016

### ISSUE THREAD

**Issue by fcaivano** [TodoPago/SDK-PHP#8]
Hola,

El siguiente error devuelto:

> Ha habido un error. Por favor inténtelo de nuevo. Error 1016

No esta documentado. Saben a que se debe?

No cambiamos nada de la aplicación y todos los campos siguen siendo enviados como hace 3-4 meses. Hubo algún breaking change?

**Comment by pcha** [comment]
Mismo que en https://github.com/TodoPago/SDK-PHP/issues/7
