### ISSUE TITLE
Server de producción caído!

### ISSUE THREAD

**Issue by lucianoghione** [TodoPago/SDK-PHP#80]
Hola, buenos días!

Hay un problema con el server de producción, esta caído hace aproximadamente 3 horas.

Estoy usando el SDK PHP 1.10.1. 

El error que arroja es: "Could not connect to host"

**Comment by curcio79** [comment]
@lucianoghione buenos dias, estamos teniendo problemas, apenas se recupere te aviso.

**Comment by curcio79** [comment]
@lucianoghione buenos dias, el servicio esta online nuevamente. Podrias verificarlo?
