### ISSUE TITLE
Problema integrando api de prismamediosdepago

### ISSUE THREAD

**Issue by ahK6** [TodoPago/SDK-PHP#82]
Hola, buenos días. 

Estoy tratando de integrar mi tienda por medio de la api de prisma la cual es la siguiente:

https://api-sandbox.prismamediosdepago.com/v1/todo_pago/merchant_payments_form/authorize_payment/{merchant_id}

pero al poner el merchant_id proporcionado por todopago siempre me devuelve un error 404, code tp-404.
Ya probe con los datos de prueba que tiene prisma y con esos si funciona todo bien.

Las disculpas por escribir aqui este incoveniente, pero el soporte de prisma dijo que se preguntara aqui y no sabia en cual de todos los repositorios escribir.

La api se quiere integrar en un sistema desarrollado con reactJS

De antemano, gracias

**Comment by curcio79** [comment]
@ahK6 buenos dias, ahi consulte internamente como seguir con el proceso. Apenas tenga la info te contacto por este medio. Dejo el ticket abierto para eso. Saludos

**Comment by curcio79** [comment]
@ahK6 por favor escribime a la cuenta ccurcio@prismamp.com. Asi te derivo a una persona encargada de tu issue. Saludos
