### ISSUE TITLE
Pagos no respetan el plazo de acreditación seleccionado en el sitio

### ISSUE THREAD

**Issue by andreszs** [TodoPago/SDK-PHP#84]
Estimados, usando la API actual 1.10.0, hice un pago real con una tarjeta prepaga de Mercadopago, y me encuentro que el mismo será acreditado en **15 dias**. El sitio ha sido configurado para **2 dias con débito** y **1 dia con crédito**, como se ven en las imagenes, pero esto es totalmente ignorado.

![image](https://user-images.githubusercontent.com/10298071/140828550-09679651-4ecf-42e4-90c4-10c7f90293c2.png)

![image](https://user-images.githubusercontent.com/10298071/140829746-afc5c5b4-2ed8-4c8b-b137-aea7f42d2bdd.png)

**Comment by curcio79** [comment]
@andreszs perdon por la falta de respuesta, podes enviarme a mi mail ccurcio@prismamp.com tu id de cuenta y si podes el nro de transaccion de la captura, asi vemos q sucedio?

Saludos
