### ISSUE TITLE
Problemas con función sendAuthorizeRequest y el parámetro CSBTIPADDRESS. Soporte para IPv6.

### ISSUE THREAD

**Issue by seraguirre** [TodoPago/SDK-PHP#85]
# SDK-PHP | Issue Técnico

## Comportamiento esperado
> SUCCESS para el client IP con formato IPv6

## Comportamiento actual
> ERROR: El formato del campo CSBTIPADDRESS es incorrecto (IPv4)

## Pasos a reproducir
> Llamar a $connector->sendAuthorizeRequest($optionsSAR_mer, $optionsSAR_op); Utilizando en el campo "CSBTIPADDRESS" una IPv6 en lugar de IPv4

## Entorno
> Completar con las versiones de las distintas herramientas aplicadas.
+ Entorno
  * __SO: Linux
  * __Servidor Web y versión: Apache/2.4.52 (Unix)
  * __Versión de PHP: PHP 7.1 FPM
  * __Versión de SDK: https://github.com/TodoPago/SDK-PHP
  * __Ambiente de Todopago: PRODUCCION

## Comentario
La función sendAuthorizeRequest devuelve ERROR cuando la ip del usuario es IPv6. Sólo soporta formato IPv4.
Debería soportar ambos formatos.

**Comment by curcio79** [comment]
@seraguirre buenos tardes, si lo q indicas es un error q ya esta reportado. si queres te paso una funcion para la conversion.

Saludos y disculpa las molestias

**Comment by seraguirre** [comment]
> @seraguirre buenos tardes, si lo q indicas es un error q ya esta reportado. si queres te paso una funcion para la conversion.
> 
> Saludos y disculpa las molestias

Perfecto! Si podés pasamela así la pruebo. Gracias.

**Comment by curcio79** [comment]
Te la paso, cualquier cosa avisame y lo vemos. El codigo ya esta implementado en el siguiente repo
https://github.com/curcio79/SDK-PHP
=========================
public function convertIPV4toIPV6($ip)
	{
		if(!ip2long($ip))
		{
			$ip = hexdec(substr($ip, 0, 2)). "." . hexdec(substr($ip, 2, 2)). "." . hexdec(substr($ip, 5, 2)). "." . hexdec(substr($ip, 7, 2));
		}
		return $ip;
	}

=========================
Saludos

**Comment by seraguirre** [comment]
> Te la paso, cualquier cosa avisame y lo vemos. El codigo ya esta implementado en el siguiente repo https://github.com/curcio79/SDK-PHP
> 
> ========================= public function convertIPV4toIPV6($ip) { if(!ip2long($ip)) { $ip = hexdec(substr($ip, 0, 2)). "." . hexdec(substr($ip, 2, 2)). "." . hexdec(substr($ip, 5, 2)). "." . hexdec(substr($ip, 7, 2)); } return $ip; }
> 
> ========================= Saludos

Ojo que la conversión genera una IPv4, pero no tiene nada que ver con el usuario. Por ejemplo, una IPv6 de Argentina, cuando la paso por tu conversor, me devuelve una IPv4 de Estados Unidos.

**Comment by curcio79** [comment]
Si, no te preocupes por eso. Te funciono bien?
Saludos
