### ISSUE TITLE
No existe un método para Cancelar un pago

### ISSUE THREAD

**Issue by jpmayoral** [TodoPago/SDK-PHP#9]
Hola! Por lo que vi en el SDK, no existe ningún método para cancelar un pago. El problema radica en que si un cliente abandona la ventana de pago no tenemos forma de cancelarlo después de X tiempo.

Tampoco vi un parámetro de expiración de pago.

Tienen pensado agregar esto?

Saludos!

**Comment by drarko** [comment]
Buenos días estimado.

La expiración del pago esta en el roadmap. 
Mantendremos al tanto de las actualizaciones

Saludos
